<?php
if (!empty($_widget_data['err_msg'])) {
    echo '<p class="error">'.$_widget_data['err_msg'].'</p>';
}
if (!$_widget_data['closed_com']) {
?>
<div id="combox" style="line-height:2em;">
	<form method="post" action="">
		<h3 id="leavecom"><a id="postcom">Commenter cet article</a></h3>
		<input class="input_com" type="text" name="pseudo" id="pseudo" />
		<label for="pseudo">Pseudo </label><br/>
		<input class="input_com" type="text" name="site" id="site" value="http://"/>
		<label for="site">Site web </label><br/>
		<textarea name="commentaire" id="commentaire"></textarea><br/>
		Sauvegarder mes informations : <input type="checkbox" name="savedata" /><br/>
		<input type="submit" value="Poster"/>
	</form>
</div>
<?php
}
?>
