<?php
if (!empty($_widget_data['err_msg'])) {
    echo '<p class="error">'.$_widget_data['err_msg'].'</p>';
}
if (!$_widget_data['closed_com']) {
?>
<div id="combox" style="line-height:2em;">
    <script type="text/javascript">
     var RecaptchaOptions = {
        theme : 'clean',
        custom_theme_widget: 'recaptcha_widget',
        lang:'fr',
     };
    </script>
	<form method="post" action="">
		<h3 id="leavecom"><a id="postcom">Commenter cet article</a></h3>
		<input class="input_com" type="text" name="pseudo" id="pseudo" />
		<label for="pseudo">Pseudo </label><br/>
		<input class="input_com" type="text" name="mail" id="mail" />
		<label for="mail">Email</label><br/>
		<input class="input_com" type="text" name="site" id="site" value="http://"/>
		<label for="site">Site web </label><br/>
		<textarea name="commentaire" id="commentaire"></textarea><br/>
		Sauvegarder mes informations : <input type="checkbox" name="savedata" /><br/>
        <?php
        require_once('libraries/recaptchalib.php');
        $publickey = "6LcHPNISAAAAAItdQK-EOMb1P5d18AGST55v3urq";
        echo recaptcha_get_html($publickey);
        ?>
        <p id="add_submit" class="right_aligned"></p>
<script>
jQuery(function ($) {
    $('#add_submit').html('<input type="submit" value="Poster" />')
});
</script>
	</form>
</div>
<?php
}
?>
