<?php
$closed_com = $view->article->closed_com;
$captcha_com = $view->article->captcha_com;
?>
<article class="post" itemprop='blogPost' itemscope='itemscope' itemtype='http://schema.org/BlogPosting'>
    <meta content='<?php echo $view->article->id; ?>' itemprop='postId'/>
    <meta itemprop="inLanguage" content="fr-FR"/>
    <header>
        <?php
        if($view->article->ecart < 0){
            $jour = floor(-$view->article->ecart/(3600*24));
            $heure = floor((-$view->article->ecart-$jour*3600*24)/3600);
            $minutes = floor((-$view->article->ecart-$jour*3600*24-$heure*3600)/60);
            echo "<span style=\"color:red;\"> Cet article sera publié dans ".$jour." jours ".$heure." heures et ".$minutes." minutes.</span><br/>";
        }
        ?>
        <div class="postDate">
            <span itemprop='datePublished' title='<?php echo str_replace(' ', 'T', $view->article->pubdate); ?>'>
                <div><?php echo $view->article->day; ?></div>
                <div><?php echo $view->article->month; ?></div>
                <div><?php echo $view->article->year; ?></div>
            </span>
	    </div>
        <div class="postTitle" itemprop='name'>
            <a href="art-<?php echo $view->article->url; ?>-<?php echo $view->article->id; ?>">
                <?php echo stripslashes($view->article->titre); ?>
            </a>
        </div>
        <span class="categorie" itemprop="about">
            <a href="cat-<?php echo $view->article->category->slug; ?>-<?php echo $view->article->category->id; ?>">
                <?php echo $view->article->category->titre; ?>
            </a>
        </span>
    </header>
    <div class="clear"></div>
    <div class="mainpost">
        <div class="postcontent" itemprop='description articleBody'>
            <?php echo stripslashes(
                       str_replace('</br>', '<br />', $view->article->texte)); ?>
            <br/><br/>
        </div>
    </div>
    <span class="tags" itemprop="about">
        <?php $i = 0; ?>
        <?php foreach ($view->article->get_tags() as $t): ?>
            <?php if ($i) { echo " - "; } ?>
        <a href="tag-<?php echo $t->slug; ?>-<?php echo $t->id; ?>">
            <?php echo utf8_decode($t->name); ?>
        </a>
            <?php $i = 1; ?>
        <?php endforeach; ?>
    </span>
    <hr />
    <div>
        <?php if (!empty($view->next_article->id)): ?>
        <span class="page_link" style="float: left;">
        <a title="<?= $view->next_article->titre; ?>"
           href="art-<?= $view->next_article->url; ?>-<?= $view->next_article->id; ?>">
            <span class="arrow">←</span> NEWER</a>
        </span>
        <?php endif; ?>
        <?php if (!empty($view->prev_article->id)): ?>
        <span class="page_link" style="float: right;">
        <a title="<?= $view->prev_article->titre; ?>"
           href="art-<?= $view->prev_article->url; ?>-<?= $view->prev_article->id; ?>">
        OLDER <span class="arrow">→</span></a>
        </span>
        <?php endif; ?>
    </div>
    <footer class="comconteneur">
<?php /*        <a class="like_link" href="<?php echo $view->article->id; ?>">
            J'aime (<span id="likes-<?php echo $view->article->id; ?>"><?php echo $view->article->nb_likes; ?></span>)
        </a>
        <?php */
        if(!empty($_SESSION['ok']) && $_SESSION['ok'] == 1){
            echo " - <a class=\"comlink\" href=\"article_edit-".$view->article->id."\">Editer</a> - 
            <a class=\"comlink\" href=\"article_delete-".$view->article->id."\">Supprimer</a><br/>";
        }
        ?>
        <section>
            <?php echo $_widgets['view_comments'];
            echo $_widgets['new_comment']; ?>
        </section>
    </footer>
<br/>
</article>
