<?php
$closed_com = $view->article->closed_com;
$captcha_com = $view->article->captcha_com;
?>
<div class="post">
    <span class="categorie">
        <?php echo $view->article->category->titre; ?>
    </span>
    <h2 class="postTitle">
        <a href="art-<?php echo $view->article->url; ?>-<?php echo $view->article->id; ?>">
            <?php echo stripslashes($view->article->titre); ?>
        </a>
    </h2>
    <br/><br/>
    <div class="mainpost">
        <div class="postcontent">
            <?php echo stripslashes($view->article->texte); ?>
            <br/><br/>
        </div>
    </div>
    <div class="comconteneur">
        <?php 
        if(!empty($_SESSION['ok']) && $_SESSION['ok'] == 1){
            echo " - <a class=\"comlink\" href=\"article_edit-".$view->article->id."\">Editer</a> - 
            <a class=\"comlink\" href=\"article_delete-".$view->article->id."\">Supprimer</a><br/>";
        }
        ?>
        <span class="postDate">
        <?php
            if($view->article->ecart < 0){
                $jour = floor(-$view->article->ecart/(3600*24));
                $heure = floor((-$view->article->ecart-$jour*3600*24)/3600);
                $minutes = floor((-$view->article->ecart-$jour*3600*24-$heure*3600)/60);
                echo "<span style=\"color:red;\"> Cet article sera publié dans ".$jour." jours ".$heure." heures et ".$minutes." minutes.</span><br/>";
            }
        ?>
            Écrit le <?php echo $view->article->post_date; ?> par <?php echo stripslashes($view->article->auteur); ?>
        </span>
        <?php echo $_widgets['view_comments'];
        echo $_widgets['new_comment']; ?>
    </div>
    <br/>
</div>
