<?php
if(!empty($view->msg)){
    echo "<p>".$view->msg."</p>";
}
if (!empty($view->sent)) {
    ?>Édité. Lien vers l'<a href="art-<?php echo $view->url; ?>-<?php echo $view->art_id; ?>">article</a><?php
}
?>
<div class="comconteneur">
	<form method="post" action="">
        <?php if (!empty($view->art_id)) { ?>
            <h3 id="leavecom"><a href="#">Édition de « <?php echo $view->titre; ?> »</a></h3>
        <?php } else { ?>
            <h3 id="leavecom"><a href="#">Ajouter un article</a></h3>
        <?php } ?>
        <input class="input_com" type="text" name="auteur" id="auteur" value="<?php echo (!empty($view->auteur)) ? $view->auteur : 'Melmelboo';?>" />
        <label for="auteur">Auteur</label><br />
        <input class="input_com" type="text" name="titre" id="titre" value="<?php echo (!empty($view->titre)) ? $view->titre : '';?>" />
        <label for="titre">Titre</label><br />
        <select class="input_com" name="cat" id="cat">
        <?php
        foreach($view->list_cat as $cat){
            if(!empty($view->cat) && $cat->id == $view->cat){
                $selected = 'selected';
            } else {
                $selected = '';
            }
            echo '<option value="'.$cat->id.'" '.$selected.'>'.$cat->titre.'</option>';
        }
        ?>
        </select>
        <label for="cat">Catégorie</label><br />
        <textarea class="new_art" name="texte" id="commentaire"><?php echo (!empty($view->art)) ? $view->art : '<img style="width: 100%;" src="http://www.melmelboo.fr/img/articles/2013/Embrun006.JPG" alt="Embrun" />
<br/><br/>';?></textarea><br /><br />
        <input class="input_com" type="text" name="pub" id="pub" value="<?php echo (!empty($view->pubdate)) ? $view->pubdate : $view->now; ?>" />
        <label for="pub">Date de publication de l'article(AAAA-MM-JJ HH-MM-SS)</label><br />
        <label for="tags">Tags : </label><br />
        <?php foreach($view->tags as $t): ?>
            <input type="checkbox"
                name="tag_<?php echo $t->id; ?>"
                <?php if (in_array($t->id, $view->art_tags)) { echo "checked"; } ?>/>
                <?php echo $t->name; ?><br />
        <?php endforeach; ?>
        <br />
        <?php if (!empty($view->art_id)) { ?>
        <input type="hidden" name="art_id" value="<?php echo $view->art_id; ?>" id="art_id" />
        <?php } ?>
        <input type="submit" value="Envoyer" />
	</form>
	Besoin d'aide pour de la mise en page ? <strong><a target="_blank" href="helphtml">C'est par ici.</a></strong> (Attention si tu ne veux pas perdre ce que tu es en train d'écrire, ouvre le lien dans un nouvel onglet.)
</div>
