<div class="center postTitle"><a href="#">Projet 52</a></div>
<div class="center postcontent"><em>- Un portrait de ma fille, chaque semaine, en 2015 -</em></div>
<br />
<div id="project_52_page">
<?php foreach ($view->images as $img): ?>
    <a href="art-<?= $img['url']; ?>-<?= $img['id']; ?>">
        <div class="grey_overlay" data-content="<?= $img['titre']; ?>">
            <?= $img['image']; ?>
        </div>
    </a>
<?php endforeach; ?>
</div>
