<?php echo count($view->comments); ?> commentaires non lus : <br/>
<form method="post" action="">
<input type="submit" name="read" value="Marquer comme lu" />
<input type="submit" name="ban" value="Bannir" />
<table class="sortable">
    <thead>
        <tr>
            <td>Pseudo</td>
            <td>IP</td>
            <td>Article</td>
            <td>Action</td>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach($view->comments as $com){
        ?>
        <tr>
            <td><?php echo $com['com']['pseudo']; ?></td>
            <td><?php echo $com['com']['ip']; ?></td>
            <td><a href="mark_comment/<?php echo $com['idcom'].'/'.$com['idarticle']; ?>">
                    <?php echo $com['article']->titre; ?>
                </a>
            </td>
            <td>
                <input type="checkbox" name="com_id[]" value="<?php echo $com['idcom']; ?>" />
            </td>
        </tr>
        <?php 
    }
    ?>
    </tbody>
</table>
</form>
<a href="mark_read_all_comments">Tout marquer comme lu</a>
