<?php echo count($view->comments); ?> commentaires non lus : <br/>
<ul>
    <?php
    foreach($view->comments as $com){
        echo '
            <li>
                Commentaire de '.$com['com']['pseudo'].' ('.$com['com']['ip'].'
                <a href="ban_ip/'.$com['com']['ip'].'"  onclick="return confirm(\'Are you sure?\')">bannir</a>)
                dans l\'article 
                <a href="mark_comment/'.$com['idcom'].'/'.$com['idarticle'].'">
                    '.$com['article']->titre.'
                </a>
            </li>';
    }
    ?>
</ul>
<a href="mark_read_all_comments">Tout marquer comme lu</a>

