<h2>Liste des catégories</h2>
<table>
	<tr>
		<th>Titre</th>
		<th>Résumé</th>
		<th>Type</th>
		<th>Modifier</th>
		<th>Supprimer</th>
	</tr>
	<?php
	foreach($view->list_cat as $cat){
		?>
		<tr>
			<td><?php echo $cat->titre; ?></td>
			<td><?php echo substr(stripslashes($cat->abstract),0,20)."..."; ?></td>
			<td><?php echo $view->cat_type[$cat->type]; ?></td>
			<td><a href="mod_cat/<?php echo $cat->id; ?>">Modifier</a></td>
			<td><a onclick="return confirm('Êtes-vous sûr de vouloir supprimer la catégorie <?php echo $cat->titre; ?>')" href="del_cat/<?php echo $cat->id; ?>">Supprimer</a></td>
		</tr>
		<?php
	}
	?>
</table>

