<a href="#" id="firstcom"></a>
<div id="com">
    <br />
    <hr/>
    <?php
    if (!empty($_widget_data['comments'])) {
    ?>
    <br />
    <span id="commentaire" class="title-font"><a href="#">Commentaires</a></span>
    <?php
    }
    foreach ($_widget_data['comments'] as $com) {
        if (strtolower($com['pseudo']) == "melmelboo") {
            $site = "http://www.melmelboo.fr";
            $class = "melmelboo";
        } elseif(!empty($com['site'])) {
            if (strlen($com['site']) > 10) {
                $site = $com['site'];
            } else {
                $site = "";
            }
            $class = "";
        } ?>
        <article class="entry" itemprop="UserComments" itemscope="itemscope" itemtype="http://schema.org/UserComments">
            <p>
                <header>
                <strong class="pseudo">
                <span itemprop="creator" itemscope="itemscope" itemtype="Person">
                    <?php if (!empty($site)) { ?>
                        <meta content="<?= $site; ?>" itemprop="url"/>
                        <a class="<?= $class; ?>" href="<?= $site; ?>">
                        <span itemprop="name"><?= htmlspecialchars($com['pseudo']); ?></span></a>
                    <?php } else { ?>
                        <span itemprop="name"><?= htmlspecialchars($com['pseudo']); ?></span>
                    <?php } ?>
                </span>
                </strong>
                <?php if($_widget_data['admin']){
                    echo ' ('.$com['ip'].', <a mailto="'.$com['mail'].'">'.$com['mail'].'</a>)';
                    ?><a href="delete_comment/<?= $com['id']; ?>">Supprimer ce commentaire</a><?php
                } ?>
                <br/>
                <small><span itemprop="commentTime"><?= $com['day']. " ".$com['month']. " " .$com['year']; ?></span></small><br/>
                </header>
                <div class="com_content" itemprop="commentText">
                    <?= nl2br(
                               stripslashes(
                               htmlspecialchars($com['commentaire']))); ?>
                </div>
            </p>
            <hr/>
        </article>
    <?php } ?>
</div>
