(1, NULL, 'Google Image', 'Googlebot-Image', 'http://images.google.com/', '', NULL),
(2, NULL, 'Google-Adsense', 'Mediapartners-Google', NULL, '', NULL),
(3, NULL, 'FeedFetcher-Google', 'FeedFetcher-Google', NULL, '', NULL),
(4, NULL, 'Google-Sitemaps', 'Google-Sitemaps', NULL, '', NULL),
(5, NULL, 'Googlebot/xx', 'Googlebot/', '', '', NULL),
(6, NULL, 'Yahoo!', 'Yahoo! Slurp', NULL, '', NULL),
(7, NULL, 'Altavista', 'Scooter', 'http://www.altavista.com', 'Moteur de recherche', NULL),
(8, NULL, 'Gigablast', 'Gigabot', 'http://www.gigablast.com/spider.html', 'Moteur de recherche', NULL),
(9, NULL, 'Sogou', 'Sogou web spider', 'http://www.sogou.com/docs/help/webmasters.htm#07', 'Chinese Search Engine', NULL),
(10, NULL, 'Voila', 'VoilaBot', 'http://www.voila.com', '', NULL),
(11, NULL, 'MSN', 'msnbot/', 'http://search.msn.com/msnbot.htm', '', NULL),
(12, NULL, 'entireweb', 'Speedy Spider', 'http://www.entireweb.com', 'Moteur de recherche', NULL),
(13, NULL, 'www.cuill.com', 'Twiceler', 'http://www.cuill.com/twiceler/robot.html', 'Moteur de recherche trés bien.', NULL),
(14, NULL, 'www.super.info', 'superbot.com', 'http://www.super.info', 'Moteur de recherche', NULL),
(15, NULL, 'Exalead', 'Exabot', 'http://www.exalead.fr', 'Moteur de recherche', NULL),
(16, NULL, 'www.baidu.com', 'Baiduspider', 'http://www.baidu.com/search/spider_jp.html', 'Chinese Search Engine', NULL),
(17, NULL, 'soso.com', 'Sosoimagespider', 'http://www.soso.com', 'Chinese picture Search Engine', NULL),
(18, NULL, 'www.discoveryengine.com', 'discobot', 'http://www.discoveryengine.com/discobot.html', 'Discobot is the experimental web crawler', NULL),
(19, NULL, 'www.shopwiki.com', 'ShopWiki', 'http://www.shopwiki.com/wiki/Help:Bot', '', NULL),
(20, NULL, 'GnoZtiK', 'GnoZtiK bot', 'http://www.gnoztik.com/', 'Site pour optimiser le référencement', NULL),
(21, NULL, 'www.yandex.ru', 'Yandex', 'http://www.yandex.ru', 'Moteur de recherche Russe', NULL),
(22, NULL, 'Xenu Link', 'Xenu Link', 'http://www.google.fr/search?hl=fr&q=xenu&btnG=Rechercher&meta=lr%3Dlang_fr', 'Test des liens morts', NULL),
(23, NULL, 'libwww-perl', 'libwww-perl', 'http://search.cpan.org/dist/libwww-perl/', 'Attention, il peut chercher des failles', NULL),
(24, NULL, 'Alexa Web Search', 'ia_archiver', 'http://www.alexa.com', 'Statistiques sites', NULL),
(25, NULL, 'Whois Source', 'SurveyBot', 'http://www.whois.sc/info/webmasters/surveybot.html', 'www.whois.sc', NULL),
(26, NULL, 'ask', 'Ask Jeeves', 'http://fr.ask.com', 'Moteur de recherche', NULL),
(27, NULL, 'DMOZ', 'Robozilla', 'http://www.dmoz.org', 'Open Directory Project', NULL),
(28, NULL, 'Sqworm', 'Sqworm', NULL, 'No idea about this one', NULL),
(29, NULL, 'Microsoft', 'msnbot-media', 'http://search.msn.com/msnbot.htm', '', NULL),
(30, NULL, 'Larbin', 'larbin_2.6.3', 'http://larbin.sourceforge.net/index-eng.html', 'Multi-purpose web crawler', NULL),
(31, NULL, 'betaBot', 'betaBot', NULL, 'Pas d''info', NULL),
(32, NULL, 'www.scoutjet.com', 'ScoutJet', 'http://www.scoutjet.com', 'ScoutJet est le robot d''exploration du Web pour une nouvelle Silicon Valley moteur de recherche créé par les fondateurs de DMOZ et Topix.', NULL),
(33, NULL, 'gossamer-threads.com', 'Links SQL', 'http://gossamer-threads.com', '', NULL),
(34, NULL, 'HTTPConnect', 'HTTPConnect', '', 'Aspirateur de site', NULL),
(35, NULL, 'Heritrix', 'heritrix/2.0.0', 'http://crawler.archive.org', 'Internet Archive''s open-source', NULL),
(36, NULL, 'www.snap.com', 'Snapbot/1.0', 'http://www.snap.com', '', NULL),
(37, NULL, 'Commoncrawl', 'CCBot/1.0', 'http://www.commoncrawl.org/bot.html', '', NULL),
(38, NULL, 'HTMLParser', 'HTMLParser', 'http://htmlparser.sourceforge.net/', 'Extraction des liens d’une page web', NULL),
(39, NULL, 'Ichiro', 'Ichiro/', 'http://help.goo.ne.jp/door/crawler.html', 'Chinese Search Engine', NULL),
(40, NULL, 'Nutch', 'nutch/Nutch', 'http://lucene.apache.org/nutch/bot.html', 'Open source project', NULL),
(41, NULL, 'FDSE robot', 'FDSE robot', NULL, '', NULL),
(42, NULL, 'RAYSPIDER/Nutch-0.9', 'RAYSPIDER/Nutch-0.9', NULL, 'I can''t find much info on this', NULL),
(43, NULL, 'Exooba', 'exooba crawler/0.5.1', 'http://www.exooba.com', 'exooba crawler for exooba search pre-alpha development', NULL),
(44, NULL, 'AdsBot-Google', 'AdsBot-Google', 'http://www.google.com/adsbot.html', 'AdWords', NULL),
(45, NULL, 'QEAVis', 'QEAVis agent/Nutch-0.9', 'http://nlp.uned.es/qeavis', NULL, NULL),
(46, NULL, 'Google', 'Google Keyword Tool', 'https://adwords.google.com/select/KeywordToolExternal', 'Générateur de mots clés', NULL),
(47, NULL, 'Exalead', 'NG/2.0', 'http://www.exalead.com/cgi/exalead', 'Moteur de recherche', NULL),
(48, NULL, ' ? Onetime Program ?', 'Onetime Program', NULL, NULL, NULL),
(49, NULL, 'page_verifier', 'page_verifier', 'http://www.securecomputing.com/goto/pv', NULL, NULL),
(50, NULL, 'Tipiweb/Nutch-0.9', 'Tipiweb/Nutch-0.9', NULL, 'Pas d''info', NULL),
(51, NULL, 'www.visvo.com', 'VisBot/2.0', 'http://www.visvo.com/bot.html', 'Petit moteur de recherche qui ne fonctionne pas bien.', NULL),
(52, NULL, 'www.rankiva.com', 'Rankivabot', 'http://www.rankiva.com', 'Rankiva is an online tool that ranks websites.', NULL),
(53, NULL, 'gossamer-threads.com', 'Links 2.0', 'http://gossamer-threads.com/scripts/links/', NULL, NULL),
(54, NULL, 'Java/1.6.0_10-beta', 'Java/1.6.0_10-beta', NULL, 'First Seen On: 24/05/2008', NULL),
(55, NULL, 'Scrubby', 'Scrubby', 'http://www.scrubtheweb.com/abs/meta-check.html', 'META Tag Analyzer', NULL),
(56, NULL, 'Python-urllib', 'Python-urllib', 'http://www.lib.uchicago.edu/keith/courses/python/class/7/', 'Phyton Module for fetching data across the World Wide Web', NULL),
(57, NULL, 'Cyberpatrol', 'CyberPatrol SiteCat Webbot', 'http://www.cyberpatrol.com/cyberpatrolcrawler.asp', 'Logiciel de contrôle parental', NULL),
(58, NULL, 'Flatlandindustries', 'flatlandbot/flatlandbot', 'http://www.flatlandindustries.com', 'Experimental Web Index', NULL),
(59, NULL, 'Metadatalabs', 'MLBot', 'http://www.metadatalabs.com/mlbot', NULL, NULL),
(60, NULL, 'kalooga', 'KaloogaBot', 'http://www.kalooga.com', 'Moteur de recherche', NULL),
(61, NULL, 'Grub', 'Grub/2.0', 'http://www.grub.org', NULL, NULL),
(62, NULL, 'Exalead', 'Exabot-Thumbnails', 'http://www.exalead.com', 'Exabot-Thumbnails ne genere des thumbnails que pour les urls crawlées par Exabot', NULL),
(63, NULL, 'Yahoo! Slurp China', 'Yahoo! Slurp China', 'http://misc.yahoo.com.cn/help.html', NULL, NULL),
(64, NULL, 'Yahoo!', 'BonEcho/2.0.0.4', NULL, NULL, NULL),
(65, NULL, 'Yahoo! DE', 'Yahoo! DE Slurp', 'http://help.yahoo.com/help/us/ysearch/slurp', NULL, NULL),
(66, NULL, 'DotBot', 'DotBot/1.0.1', 'http://www.dotnetdotcom.org', NULL, NULL),
(67, NULL, 'Amfibi\\''s web-crawling', 'Cabot/Nutch-0.9', 'http://www.amfibi.com/cabot/', 'Moteur de recherche', NULL),
(68, NULL, 'Acoon', 'Acoon-Robot 4.0.2.17', 'http://www.acoon.de', 'Moteur de recherche Allemand', NULL),
(69, NULL, 'BrightCloud', 'BrightCrawler', 'http://www.brightcloud.com/brightcrawler.asp', NULL, NULL),
(70, NULL, 'Crawl Annu', 'Crawl Annu', NULL, 'Inconnu', NULL),
(71, NULL, 'Eurobot/Nutch', 'Eurobot/Nutch-1.0-dev', NULL, 'Inconnu', NULL),
(72, NULL, 'www.snap.com', 'SnapPreviewBot', 'http://www.snap.com', 'Snap Firefox Search Plugin', NULL),
(73, NULL, 'Yeti', 'Yeti/1.0', 'http://help.naver.com/robots/', 'chinese bot', NULL),
(74, NULL, 'Amfibi''s web-crawling', 'Cabot/Nutch-1.0-dev', 'http://www.amfibi.com/cabot/', 'Amfibi''s web-crawling robot', NULL),
(75, NULL, 'Microsoft isrc-bot', 'MSR-ISRCCrawler', NULL, '', NULL),
(76, NULL, 'panscient.com', 'panscient.com', '', 'Panscient explore le Web et recueille des informations sur les personnes et les entreprises pour des applications de recherche', NULL),
(77, NULL, 'therarestwords', 'TheRarestParser/0.2a', 'http://therarestwords.com', 'The Rarest Words - Linguistic experiment crawler via Amazon Web Services', NULL),
(78, NULL, 'www.wauuu.com', 'wauuu engine/Wauuu 0.1', 'http://www.wauuu.com', NULL, NULL),
(79, NULL, 'Microsoft Corporation', 'MSNPTC/Test', 'http://msn.com', 'No information available', NULL),
(80, NULL, 'OpenAcoon', 'OpenAcoon v4.0.3', 'http://www.openacoon.de', NULL, NULL),
(81, NULL, 'compatible; Indy Library', 'compatible; Indy Library', NULL, 'Pas d''info', NULL),
(82, NULL, 'holmes/3.12', 'holmes/3.12', 'http://morfeo.centrum.cz/bot', 'Pas d''info', NULL),
(83, NULL, 'OpenAcoon', 'OpenAcoon v4.0.5', 'http://www.openacoon.de', NULL, NULL),
(84, NULL, '', 'shelob v1.0', '', 'Bad bot', NULL),
(85, NULL, 'NetWhat', 'NetWhatCrawler/0.06-dev', 'http://www.netwhat.com', 'Moteur de recherche', NULL),
(86, NULL, 'Exooba', 'exooba crawler/exooba', 'http://www.exooba.com', 'exooba crawler for exooba search pre-alpha development', NULL),
(87, NULL, 'Exooba', 'exooba/exooba', 'http://www.exooba.com', 'exooba crawler for exooba search pre-alpha development', NULL),
(88, NULL, 'Thumbshots', 'thumbshots-de-bot', 'http://www.thumbshots.de', NULL, NULL),
(89, NULL, 'Moreover', 'Moreoverbot/5.00', 'http://www.moreover.com', NULL, NULL),
(90, NULL, 'MSIECrawler', 'MSIECrawler', NULL, 'MSIECrawler is not a true web robot. It is usually to be found in site logs if someone bookmarks a page whilst offline. Internet Explorer will then download the page and all links related to it, including links, images, JavaScript and Style sheets, when t', NULL),
(91, NULL, 'www.myengines.org', 'MyEngines-Bot', 'http://www.myengines.org', NULL, NULL),
(92, NULL, 'NetEase', 'YodaoBot/1.0', 'http://www.163.com/', 'NetEase is known for its popular Chinese portal 163.com. It was using Google as its search engine till the middle of 2007, when it decided to replace it by yodao, its own search engine.', NULL),
(93, NULL, 'Microsoft', 'MSRBOT', 'http://research.microsoft.com/research/sv/msrbot/', 'We are using the MSRBot web crawler to collect data from the web for further study.', NULL),
(94, NULL, 'quickengines.com', 'Jeanie_2008_bot/3.2', 'http://www.quickengines.com', NULL, NULL),
(95, NULL, 'PhpDig.net', 'PhpDig/1.8.0', 'http://www.phpdig.net/robot.php', NULL, NULL),
(96, NULL, 'Nokia find.mobi', 'Nokia6300/2.0', 'http://find.mobi/bot.html', NULL, NULL),
(97, NULL, 'freedownloadmanager.org', 'FDM 2.x', 'http://www.freedownloadmanager.org/', 'Free Download Manager (FDM) download accelerator', NULL),
(98, NULL, 'GoogleToolbar', 'GoogleToolbar 2.0.111-big', NULL, NULL, NULL),
(99, NULL, 'Java/1.6.0_06', 'Java/1.6.0_06', NULL, NULL, NULL),
(100, NULL, 'Touche', 'Touche', 'http://www.touche.com.ve/', 'Search engine', NULL),
(101, NULL, 'www.semager.de', 'Semager/1.2', 'http://www.semager.de/blog/semager-bots/', NULL, NULL),
(102, NULL, 'www.sigram.com', 'Sigram/Nutch-1.0-dev', 'http://www.sigram.com/bot.html', 'Test agent for Nutch development', NULL),
(103, NULL, 'WebDataCentre.com', 'WebDataCentreBot/1.0', 'http://WebDataCentre.com/', 'Projet de recherche conduit par une petite équipe de chercheurs de différentes régions du monde.', NULL),
(104, NULL, 'Sqwidge', 'SqwidgeBot a0.3.23', 'http://www.sqwidge.com/bot/', 'Développement moteur de recherche', NULL),
(105, NULL, 'setooz.com', 'OOZBOT/0.17', 'http://www.setooz.com/oozbot.html', 'Moteur de recherche', NULL),
(106, NULL, 'rulinki.ru project', 'rulinki.ru project', '', 'Non indentifié', NULL),
(107, '', 'Wikiwix', 'wikiwix-bot-3.0', 'http://www.wikiwix.com/', 'Wikipedia articles search engine', ''),
(108, '', 'Sogou', 'Sogou Pic Spider/3.0', 'http://www.sogou.com/docs/help/webmasters.htm#07', 'Chinese picture Search Engine', ''),
(109, '', 'MailWalker', 'MailWalker', 'http://www.websynaptics.com/solutions.html', 'Extracteur d''emails', ''),
(110, '', 'Jakarta Commons-HttpClient/3.0.1', 'Jakarta Commons-HttpClient/3.0.1', 'http://hc.apache.org/httpclient-3.x/', '', ''),
(111, '', 'Yahoo', 'Yahoo-MMCrawler', 'http://www.robotstxt.org/wc/exclusion.html#robotstxt', 'Recherche d''images', ''),
(112, '', 'www.picsearch.com', 'psbot/0.1', 'http://www.picsearch.com/bot.html', 'PicSearch index des images à partir du Web.', ''),
(113, '', 'Yahoo!-AdCrawler', 'Yahoo!-AdCrawler', ' http://help.yahoo.com/yahoo_adcrawler', '', ''),
(114, '', 'Reedbusiness', 'CatchBot/1.0', 'http://www.catchbot.com', 'Reed Business Information propose de l’information et de l’espace de communication B to B à travers ses 3 métiers : presse, édition et formation.', ''),
(115, '', 'WorldSearch', 'Yanga WorldSearch Bot v1.1', 'http://www.yanga.co.uk', 'Moteur de recherche', ''),
(116, '', 'Guruji', 'GurujiBot/1.0', 'http://www.guruji.com/en/WebmasterFAQ.html', 'Moteur de recherche', ''),
(117, '', 'Turnitin', 'TurnitinBot/2.1', 'http://www.turnitin.com/robot/crawlerinfo.html', 'Site permetant aux professeurs de voir si les élèves ont copié des phrases sur Internet.', ''),
(118, '', 'FollowSite', 'FollowSite Bot', 'http://www.followsite.com/bot.html', 'Votre site web est important pour un (ou plusieurs) de nos utilisateurs et a été ajouté à FollowSite. Nous allons maintenant surveiller votre site et lui notifier quand il est mis à jour.', ''),
(119, '', 'Sapphire Web Crawler using Nutch', 'SapphireWebCrawler/Nutch-1.0-dev', 'http://boston.lti.cs.cmu.edu/crawler/', 'Le projet est la création d\\''une base de données de 1 milliard de pages web en 10 langues qui seront utilisées à des fins de recherche par les scientifiques du monde entier. Le projet est supervisé par le professeur Jamie Callan.', ''),
(120, '', 'Sapphire Web Crawler using Nutch', 'SapphireWebCrawler/1.0', 'http://boston.lti.cs.cmu.edu/crawler', 'Le projet est la création d\\''une base de données de 1 milliard de pages web en 10 langues qui seront utilisées à des fins de recherche par les scientifiques du monde entier. Le projet est supervisé par le professeur Jamie Callan.', ''),
(121, '', 'dotnetdotcom', 'DotBot/1.1', 'http://www.dotnetdotcom.org', '', ''),
(122, '', 'dontbuylists.com', 'DBLBot/1.0', 'http://www.dontbuylists.com', '', ''),
(123, '', 'askpeter', 'askpeter_bot_5.0', 'http://www.askpeter.info', 'Moteur de recherche', ''),
(124, '', 'kilomonkey.com', 'kmky-not-a-bot/0.2', 'http://www.kilomonkey.com/notabot.txt', 'Pas d''infos', ''),
(125, '', 'Flatland Industries Web Spider', 'flatlandbot/baypup', 'http://www.flatlandindustries.com/flatlandbot', '', ''),
(126, '', 'first-search.com', 'FirstSearchBot/1.0', 'http://www.first-search.com', 'Moteur de recherche', ''),
(127, '', 'gais.cs.ccu.edu.tw', 'Gaisbot/3.0', 'http://gais.cs.ccu.edu.tw/robot.php', 'Développement moteur de recherche', ''),
(128, '', 'apercite.fr', 'Apercite', 'http://www.apercite.fr/robot/index.html', 'Miniature en image de votre site.', ''),
(129, '', 'askpeter.info', 'askpeter_bot/5.0', 'http://www.askpeter.info', 'Moteur de recherche', ''),
(130, '', 'bibnum.bnf.fr', 'bnf.fr_bot', 'http://bibnum.bnf.fr/robot/bnf.html', 'Vous avez été renvoyé à cette page car votre site est actuellement collecté automatiquement par la Bibliothèque nationale de France (BnF).', ''),
(131, '', 'Nokia', 'Nokia6682/2.0', 'http://help.yahoo.com/help/us/ysearch/crawling/crawling-01.html', '', ''),
(132, '', 'Nokia', 'Nokia6680/1.0', '', '', ''),
(134, '', 'SimilarPages Nutch Crawler', 'SimilarPages/Nutch-1.0-dev', 'http://www.similarpages.com', 'Pas d''infos à ce jour', ''),
(135, '', '', 'digiSelf crawler/Nutch-1.0-dev', '', 'Pas d''infos à ce jour', ''),
(136, '', 'Flatland Industries Web Spider', 'flatlandbot/allspark', 'http://www.flatlandindustries.com/flatlandbot', '', ''),
(137, '', 'Robotgenius.net', 'robotgenius', 'http://robotgenius.net', '', ''),
(138, '', 'www.kosmix.com', 'voyager/2.0', 'http://www.kosmix.com/crawler.html', 'Il récupère des documents sur le Web pour construire l''indice du moteur de recherche Kosmix ', ''),
(139, '', 'yacy.net', 'yacybot', 'http://yacy.net/bot.html', '"yacybot" est le useragent du logiciel YaCy, qui est une approche pour construire un réseau de peer-to-Peer basée websearch-moteur.', ''),
(140, '', 'ODP link checker', 'pmoz.info ODP link checker', 'http://pmoz.info/doc/botinfo.htm', 'Vérifie des liens de l\\''annuaire Dmoz Open Directory Project', ''),
(141, '', 'OrangeBot-Mobile', 'OrangeBot-Mobile', '', '', ''),
(142, '', 'afholderbach.net', 'ecoNet', 'http://www.eco.afholderbach.net', '', ''),
(143, '', 'hrinktheweb.com', 'ShrinkTheWeb.com Crawler v1.0', 'http://www.shrinktheweb.com', 'Miniature en image de votre site (thumbnail).', ''),
(144, '', 'LinguaSeek', 'LinguaSeek', 'http://www.linguaseek.com', 'Moteur de recherche', ''),
(145, '', 'W3C CSS Validator', 'W3C_CSS_Validator', 'http://jigsaw.w3.org/css-validator', 'Test W3C des feuilles CSS', ''),
(146, '', 'GSiteCrawler', 'GSiteCrawler', 'http://gsitecrawler.com/', 'Bot du logiciel pour construire le SiteMap - gsitecrawler', ''),
(147, '', 'Sosospider', 'Sosospider', 'http://help.soso.com/webspider.htm', '', ''),
(148, '', 'PHPCrawl', 'PHPCrawl', '', 'Pas d''information', ''),
(149, '', 'woozweb-monitoring', 'woozweb-monitoring', 'http://www.woozweb.com', 'observatoire du web et monitoring gratuit', ''),
(150, '', 'Tagoobot', 'Tagoobot/3.0', 'http://www.tagoo.ru', 'Exclusivement russe', ''),
(151, '', '50.nu/0.01', '50.nu/0.01', 'http://50.nu/bot.html', 'Si vous lisez ces lignes, il est probable que quelqu''un a ajouté votre site à notre base de données. Cela signifie qu''ils seront mis à jour par email ou par RSS à chaque fois votre site est mis à jour.', ''),
(152, '', 'youdao.com', 'YoudaoBot/1.0', 'http://www.youdao.com/help/webmaster/spider/', 'Exclusivement chinois', ''),
(153, '', '80legs.com', '008/0.83', 'http://www.80legs.com/spider.html', '', ''),
(154, '', 'Askpeter', 'askpeter_bot/5.1', 'http://www.askpeter.info', 'Moteur de recherche', ''),
(155, '', 'Who.is', 'Who.is Bot', 'http://who.is/', 'Information sur les noms de domaine', ''),
(156, '', 'Sogou', 'Sogou-Test-Spider/4.0', 'http://www.sogou.com/', 'Moteur de recherche chinois', ''),
(157, '', 'LinkStar', 'LinkStar Research', 'http://linkstar.com/', 'Hébergeur qui cherche à se faire des liens via les stats ?', ''),
(158, '', 'parchmenthill.com', 'ParchBot/1.0', 'http://www.parchmenthill.com/search.htm', 'Nous travaillons sur un projet spécial qui peut être décrit comme un «moteur de recherche de domaine" (ou "moteur de recherche de site Web»)', ''),
(159, '', 'W3C Validator', 'W3C_Validator', 'http://validator.w3.org/', 'Test des pages web à la norme W3C', ''),
(160, '', 'www.majestic12.co.uk', 'MJ12bot', 'http://www.majestic12.co.uk/bot.php?+', 'Ce projet porte sur la création d\\''un moteur de recherche World Wide Web reposant sur des concepts de distribution de la charge de travail', ''),
(161, '', '', 'SheenBot', '', '', ''),
(162, '', '', 'My Spider 1.0', '', '', ''),
(163, '', '', 'My Spider 1.0', '', 'No information available', ''),
(164, '', 'gingersoftware.com', 'GingerCrawler', 'http://www.gingersoftware.com/crawler_agent.htm', 'Language Assistant for Dyslexics', ''),
(165, '', 'linguee.com', 'Linguee Bot', 'http://www.linguee.comlinguee.com', 'Linguee is more than a German-English dictionary', ''),
(166, '', 'seexie.com', 'seexie.com_bot', 'http://www.seexie.com', 'Search engine', ''),
(167, '', 'Bing', 'bingbot/2.0', 'http://www.bing.com/bingbot.htm', 'Moteur de recherche Microsoft', ''),
(168, '', '360Spider', '360Spider', '', 'Inconnu', ''),
(169, '', 'TwengaBot', 'TwengaBot-2.0', '', '', ''),
(170, '', 'BingPreview', 'BingPreview', 'http://www.bing.com/bingbot.htm', 'Preview thumb of website', ''),
(171, '', 'Googlebot-Mobile', 'Googlebot-Mobile', '', '', ''),
(172, '', 'NetcraftSurveyAgent', 'NetcraftSurveyAgent/', '', 'info@netcraft.com, com, http://www.netcraft.com/ Providing internet security services', ''),
(173, '', 'SiteExplorer', 'SiteExplorer/', 'http://siteexplorer.info/', 'Recherche de backlink', ''),
(174, '', 'http://github.com/', 'Mechanize/', '(http://github.com/tenderlove/mechanize/', 'Powerful collaboration, review, and code management for open source and private development projects.', ''),
(175, '', 'go.mail.ru', 'Mail.RU_Bot/', 'http://go.mail.ru', 'Moteur de recherche Russe', ''),
(176, '', 'ratup.com', 'ratup.com bot', 'http://www.ratup.com/', 'Moteur de recherche', ''),
(177, '', 'search.msn.com', 'Detected by reverse dns: msnbot-', 'http://search.msn.com', 'Bing Search Engine (Detected by reverse dns)', ''),
(179, '', 'www.flightdeckreports.com', 'FlightDeckReportsBot/', 'http://www.flightdeckreports.com/pages/bot', 'The Flight Deck Bot is a polite web crawler. Its purpose is to better understand how web technologies are used in business.', ''),
(180, '', 'MaxPointCrawler', 'MaxPointCrawler/', '', 'Unknown', ''),
(181, '', 'www.crystalsemantics.com', 'CrystalSemanticsBot', 'http://www.crystalsemantics.com/user-agent/', 'Making sense of advertising', ''),
(182, '', 'Ara.com.tr', 'AraBot', 'http://www.ara.com.tr/', 'Turkey Search Engine', ''),
(183, '', 'www.acoon.de', 'AcoonBot/', 'http://www.acoon.de', 'German search engine', ''),
(184, '', 'ahrefs.com', 'AhrefsBot/', 'http://ahrefs.com/robot/', 'Backlink test (commercial)', ''),
(185, '', 'www.career-x.de', 'CareerBot/', 'http://www.career-x.de', 'Wir finden Jobs direkt bei den Unternehmen (German)', ''),
(186, '', 'Ezooms', 'Ezooms/', '', '', ''),
(187, '', 'www.grapeshot.co.uk', 'GrapeshotCrawler/', 'http://www.grapeshot.co.uk/crawler.php', 'Grapeshot uses advanced probabilistic algorithms to assess the relative significance of keywords in pages and what users read.', ''),
(188, '', 'shoulu.jike.com', 'JikeSpider', 'http://shoulu.jike.com/spider.html', 'chinese Search Engine', ''),
(189, '', 'http://www.netseer.com', 'NetSeer crawler/', 'http://www.netseer.com/crawler.html', 'The Only Concept-Based Contextual Advertising', ''),
(190, '', 'SISTRIX Crawler', 'SISTRIX Crawler', 'http://crawler.sistrix.net', 'Unknown', ''),
(191, '', 'www.semrush.com', 'SemrushBot/', 'http://www.semrush.com/bot.html', 'Professional Software For Search and Marketing Professionals', ''),
(192, '', 'snipebot.com', 'Snipebot/', 'http://snipebot.com/bot.html', 'Snipebot is non-commercial crawler created for the purpose of education and research', ''),
(193, '', 'www.webmah.com', 'WebMahBot/', 'http://www.webmah.com/bot.html', 'Unknown', ''),
(194, '', 'oBot', 'oBot/', 'http://filterdb.iss.net/crawler/', 'oBot is the web crawling bot of the Content Security Division of IBM Germany Research & Development GmbH. We use several computers to crawl webpages and a large computer cluster to categorize the content of these pages.', ''),
(195, '', 'www.proximic.com', 'compatible; proximic', 'http://www.proximic.com/info/spider.php', 'Commercial', ''),
(196, '', 'queryseeker.com', 'QuerySeekerSpider', 'http://queryseeker.com/bot.html', 'QuerySeeker Analyze is a Marketing Analysis Tool That Maximizes Downloads of iPhone, iPad, Android, Windows Phone Apps. It is traking App Store, Android Market, Windows Market Place, Blog and Twitter.', ''),
(197, '', 'fulltext.sblog.cz', 'SeznamBot/', 'http://fulltext.sblog.cz', 'Crawler (Czech Republic )', ''),
(198, '', 'www.wotbox.com', 'Wotbox/', 'http://www.wotbox.com/bot/', 'The Wotbox bot crawls the internet in order to discover new and updated pages. Our index is then generated by an algorithm which selects the most important pages on the web.', ''),
(199, '', 'www.fastbot.de', 'fastbot crawler beta', 'http://www.fastbot.de', 'German search engine', ''),
(201, '', '200PleaseBot/', '200PleaseBot/', 'http://www.200please.com/bot', 'Bot used to track your website performance. NOTE Test performed by : ec2-54-251-45-250.ap-southeast-1.compute.amazonaws.com ec2-54-249-240-15.ap-northeast-1.compute.amazonaws.com ec2-54-252-97-95.ap-southeast-2.compute.amazonaws.com ec2-50-112-126-117.us-', ''),
(203, '', 'facebookexternalhit', 'facebook.com/externalhit_uatext', 'http://www.facebook.com/externalhit_uatext.php', 'Detection by the url provided by the user agent, because - as usurpation possible. Facebook scrapes your page every 24 hours to ensure the properties are up to date. The page is also scraped when an admin for the Open Graph page clicks the Like button and', ''),
(204, '', 'python-requests', 'python-requests/1.2.0', 'http://docs.python-requests.org/en/latest/api/', 'Developer Interface - Bot multi use', ''),
(205, '', 'www.genieo.com', 'Genieo/', 'http://www.genieo.com/webfilter.html', '', ''),
(206, '', 'wortschatz.uni-leipzig.de', 'findlinks/', 'http://wortschatz.uni-leipzig.de/findlinks/', '', ''),
(207, '', 'www.studiofaca.com', 'StudioFACA', 'http://www.studiofaca.com/', '', ''),
(208, '', 'www.inboundscore.com', 'OppO 1.0', 'http://www.inboundscore.com', '', ''),
(209, '', 'Human cURL for python', 'human_curl.async; 0.1.1', 'http://h.wrttn.me/human_curl', 'BOT development multi use', ''),
(210, '', 'Wget', 'Wget/', '', 'Operating system Linux download', ''),
(211, '', 'Jakarta Commons-HttpClient', 'Jakarta Commons-HttpClient/', 'http://hc.apache.org/httpclient-3.x/', 'BOT development multi-purpose', ''),
(212, '', 'www.dataprovider.com', 'Dataprovider Site Explorer', 'http://www.dataprovider.com/', 'Dataprovider transforms the internet into a structured information database to create insightful information about companies.', ''),
(213, '', 'HTTrack', 'HTTrack', 'http://www.httrack.com/', 'Loading Web pages', ''),
(214, '', 'www.chilkatsoft.com', 'Chilkat/', 'http://www.chilkatsoft.com/ChilkatHttpUA.asp', 'Chilkat Software is a company that develops, markets, and sells software components and libraries to companies worldwide.  Thousands of companies use Chilkat technology for email, compression, encryption, FTP, HTTP, and other Internet technologies.', ''),
(215, '', 'fulltext.sblog.cz', 'Seznam screenshot-generator', 'http://fulltext.sblog.cz/screenshot/', 'Czech Republic', ''),
(216, '', 'Riddler', 'Riddler', 'http://riddler.io/about.html', 'Riddler is an online research project which investigates algorithms for mapping the topology of the Internet. Riddler collects data about public systems via crawling and port mapping common ports.', ''),
(217, '', 'WordPress', 'WordPress/', 'Multiple usage', 'A voir', ''),
(218, '', 'www.openindex.io', 'OpenindexSpider', 'http://www.openindex.io/en/webmasters/spider.html', 'Commercial', ''),
(219, '', 'Google Web Preview', 'Google Web Preview', '', 'Preview thumb of website', ''),
(220, '', 'ThumbShotsBot', 'ThumbShotsBot', 'http://www.thumbshots.de/content-24-thumbshot_info.html', 'German', ''),
(221, '', 'CompSpyBot', 'CompSpyBot/', 'http://www.compspy.com/spider.html', '', ''),
(222, '', 'emefge.de', 'emefgebot/', 'http://emefge.de/bot.html', 'German search engine', ''),
(223, '', 'BOneB Spider', 'BOneB Spider', '', 'Unknown', ''),
(224, '', 'SEOkicks-Robot', 'SEOkicks-Robot', 'http://www.seokicks.de/robot.html', 'German crawler', ''),
(225, '', 'OpenWebSpider', 'OpenWebSpider', 'http://www.openwebspider.org/', 'Open Source Web Spider', ''),
(226, '', 'pagesinventory.com', 'PagesInventory (robot', 'http://www.pagesinventory.com', 'PagesInventory.com is a free service that provides information about webhosting and domain names, reverse IP (+Ipv6) search and some other services', ''),
(227, '', 'www.wise-guys.nl', 'Vagabondo/', 'http://www.wise-guys.nl/', 'Commercial --> We provide spider and search technology. We spider the web 24/7, 365 days a year, resulting in one of the largest up-to-date web archives of the internet.', ''),
(228, '', 'www.abonti.com', 'Abonti/', 'http://www.abonti.com', 'Search engine under development', ''),
(229, '', 'ExaleadCloudView', 'ExaleadCloudView/', 'http://fr.3ds.exalead.com/software/products/cloudview/', 'CloudView permet aux entreprises d''améliorer considérablement l''accès à l''information pertinente, qu''il s''agisse de concevoir des services standards de recherche en entreprise ou de construire des applications métiers plus sophistiquées.', ''),
(230, '', 'LinkExaminer', 'LinkExaminer/', '', 'free Link Checker same than Xenu.  Dispo : http://www.analogx.com/contents/download/network/lnkexam/Freeware.htm', ''),
(231, '', 'Pinterest', 'Pinterest/', 'http://pinterest.com/', 'Spam ?', ''),
(232, '', 'AC-BaiduBot', 'AC-BaiduBot/', 'http://www.ac-baidu.com)', 'AC-Baidu Advertising Programs, Very Effective Ways To Reach China Market', ''),
(233, '', 'tweetmeme.com', 'TweetmemeBot/', 'http://tweetmeme.com', 'Social platform', ''),
(234, '', 'zum.com', 'ZumBot/', 'http://help.zum.com/inquiry', 'Chinese crawler', ''),
(237, '', 'ichiro/mobile', 'ichiro/mobile', 'http://search.goo.ne.jp/option/use/sub4/sub4-1/', 'Chinese Search Engine', '');
