(1, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows NT; DigExt; DTS Agent', 'Beijing Express Email Address Extractor via DHCP Data Transport Services (DTS)', 'S'),
(2, 'Mozilla/3.0 (compatible)', 'Unknown', 'A'),
(3, 'Mozilla/4.0', 'Unknown', 'A'),
(4, 'Mozilla/4.0 (compatible; Advanced Email Extractor v2.xx)', 'Advanced Email Extractor e-mail collector (spam bot)', 'S'),
(5, 'Mozilla/4.0 (compatible; Iplexx Spider/1.0 http://www.iplexx.at)', 'Iplexx Austria (webhosting company) logfile spamming bot', 'S'),
(6, 'Mozilla/4.0 (compatible;)', 'Unknown', 'A'),
(7, '8484 Boston Project v 1.0', 'Unknown guestbook spamming or harvesting tool from diff. IPs', 'S'),
(8, 'atSpider/1.0', 'atSpider (ceased) email harvester / spambot ', 'S'),
(9, 'autoemailspider', 'Auto Email Pro Email harvester', 'S'),
(10, 'bwh3_user_agent', 'Basic Web Hacking 3 fake user-agent from Hellbound Hackers challenges', 'S'),
(11, 'ContactBot/0.2', 'Probably E-Mail harvesting robot - same as LMQueueBot', 'S'),
(12, 'ContentSmartz', 'ContentSmartz e-mail harvesting tools', 'S'),
(13, 'DataCha0s/2.0', 'Unknown bot from Kornet Korea (218.149.129.xxx) scans for Perl Awstats', 'S'),
(14, 'DBrowse 1.4d', 'Some site scanning tool via diff. IPs i.e.: - pacbell.net (67.112.xxx.xxx)', 'S'),
(15, 'Demo Bot DOT 16b', 'Some site scanning tool from 217.34.59.xxx (btopenworld.com)', 'S'),
(16, 'Demo Bot Z 16b', 'Some site scanning tool from 68.154.96.xx (bellsouth.net)', 'S'),
(17, 'DSurf15a 01', 'Some site scanning tool via diff. IPs i.e.: - cox.net (68.5.xxx.xxx) - pacbell.net (64.16x.xxx.xxx)', 'S'),
(18, 'DSurf15a 71', 'Some site scanning tool via diff. IPs i.e.: - cox.net (68.4.xxx.xxx)', 'S'),
(19, 'DSurf15a 81', 'Some site scanning tool via diff. IPs i.e.: - verizon.net (4.47.xxx.xxx)', 'S'),
(20, 'DSurf15a VA', 'Some site scanning tool via diff. IPs i.e.: - eastlink.ca (24.222.xxx.xxx) - cogeco.net (216.221.8x.xxx)', 'S'),
(21, 'EBrowse 1.4b', 'Some site scanning tool via diff. IPs i.e.: - swbell.net (65.66.xxx.xxx)', 'S'),
(22, 'Educate Search VxB', 'Some site scanning tool via diff. IPs i.e.: - cox.net (68.4.xxx.xxx)', 'S'),
(23, 'EmailSiphon', 'Sonic E-mail collector', 'S'),
(24, 'EmailSpider', 'EmailSpider E-mail harvesting software', 'S'),
(25, 'EmailWolf 1.00', 'Trellian EMailWolf E-mail collector', 'S'),
(26, 'ESurf15a 15', 'Some site scanning tool via diff. IPs ', 'S'),
(27, 'ExtractorPro', 'Extractor Pro e-mail collector', 'S'),
(28, 'Franklin Locator 1.8', 'Some spam bot', 'S'),
(29, 'FSurf15a 01', 'Some site scanning tool via diff. IPs', 'S'),
(30, 'Full Web Bot 0416B', 'Some site scanning tool from diff. IPs i.e.: - 66.28.240.xx (cogentco.com) - 68.5.174.xx (cox.net)', 'S'),
(31, 'Full Web Bot 0516B', 'Some site scanning tool i.e. from - 68.154.96.xx (bellsouth.net)', 'S'),
(32, 'Full Web Bot 2816B', 'Some site scanning tool from 66.255.6.xxx (uslec.com)', 'S'),
(33, 'China Local Browse 2.6', 'Unknown spam bot from telekom.com.my (218.111.83.xxx)', 'S'),
(34, 'Industry Program 1.0.x', 'Spam bot from diff. IPs', 'S'),
(35, 'IUPUI Research Bot v 1.9a', 'Some spam bot from 66.139.78.xx(x)', 'S'),
(36, 'Lincoln State Web Browser', 'Some spam bot', 'S'),
(37, 'LWP::Simple/5.803', 'ThePlanet/jaja-jak-globusy.com Google Adsense refferer spam bot from 70.85.116.* / 70.84.128.xxx / 70.85.193.xxx', 'S'),
(38, 'Mac Finder 1.0.xx', 'Some spam bot', 'S'),
(39, 'Missauga Locate 1.0.0', 'Some spam bot', 'S'),
(40, 'Mozilla/5.0', 'Unknown', 'A'),
(41, 'http://Anonymouse.org/ (Unix)', 'Anonymous web proxy service', 'A'),
(42, 'InetURL:/1.0', 'InetURL IVM (phone software) plugin for web server access ?', 'A'),
(43, 'Mozilla/4.0+(compatible;+MSIE+6.0;+Windows+NT+5.1)', 'Unknown at this time', 'I'),
(44, 'Netvibes (http://www.netvibes.com)', 'Netvibes est la manière la plus rapide de suivre votre Web temps-réel. Tout est rassemblé en un seul endroit et constamment mis à jour. Créez instantanément autant de dashboards que vous le voulez, surveillez vos derniers centres d''intérêt...', 'A'),
(45, 'Java/1.6.0_26', 'Java', 'A'),
(46, 'Web-sniffer.me/1.0.0 (+http://web-sniffer.me/)', 'For test : http://web-sniffer.me/', 'A'),
(47, 'Mozilla/5.001', 'The User agent string is incomplete', 'A'),
(48, 'Java/1.6.0_22', 'Java', 'A'),
(49, 'Java/1.6.0_04', 'Java', 'A'),
(50, 'Mozilla/5.0 (Windows; U; MSIE 9.0; WIndows NT 9.0; en-US)', 'Fake useragent', 'S'),
(51, 'Mozilla/4.0 (compatible; U; MSIE 9.0; WIndows NT 9.0; fr-FR)', 'Unknown', 'S'),
(52, 'Zend_Http_Client', 'Unknown', 'S'),
(53, 'Mozilla/5.0 (Windows NT x.y; Win64; x64; rv:10.0.1) Gecko/20100101 Firefox/10.0.1', 'Unknown User Agent', 'S'),
(54, 'Java/1.6.0_14', 'Java', 'A'),
(55, 'Garden Path', 'Unknown', 'S'),
(56, 'Java/1.6.0_31', 'Java', 'A'),
(57, 'Mozilla', 'Unknown', 'A'),
(58, 'PHP/5.2.17', 'http://php.net/', 'A'),
(59, 'Ruby', '', 'S'),
(60, 'Go http package', '', 'S'),
(61, 'Java/1.7.0_15', 'Java', 'A'),
(62, 'raynette_httprequest/1.0', '', 'A'),
(63, 'http_requester/0.1', '', 'A'),
(64, 'Web::Scraper/0.37', '', 'A'),
(65, 'testtw', '', 'A'),
(66, 'Mojolicious (Perl)', 'http://mojolicio.us/', 'A'),
(67, 'Opera 8.1', 'The User agent string is incomplete', 'A'),
(68, 'Mozilla/5.0 (000000000; 00000 000 00 0 000000) DDDDDDDDDDDDDDDDDDDD DDDDDDD DDDD DDDDDD DDDDDDDDDDDDD DDDDDDDDDDDDDDD', '', 'S'),
(69, 'Mozilla/5.0 (compatible; AlexaBoostup/1.0; +http://www.alexaboostup.com/)', '', 'S'),
(70, 'siclab (cboc-test@lab.ntt.co.jp)', '', 'S'),
(92, 'Java/1.6.0_07', 'Java', 'A'),
(72, 'Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-CA)', '', 'S'),
(75, 'Mozilla/4.0 (Windows; U; Windows NT 5.1; en-GB; rv:1.9.2.20)', 'Browser Not recognized', 'A'),
(74, 'Mozilla/4.0 (compatible; ICS)', 'Spam', 'S'),
(76, 'WordPress.com mShots; http://support.wordpress.com/contact/', '', 'A'),
(77, 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko', 'Browser Not recognized', 'A'),
(78, 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)', 'Browser Not recognized', 'A'),
(79, 'Mozilla/4.0 (compatible; MSIE 6.1; Windows NT)', 'Browser  Not recognized - Chinese', 'S'),
(80, 'Mozilla/5.0 (compatible; MSIE 3.0; Linux i686; Win64; x64; Trident/4.0)', 'Browser Not recognized - IE3 ??', 'S'),
(81, 'Content Crawler', '', 'S'),
(82, 'Mozilla/4.0 (compatible; Synapse)', 'http://wiki.apache.org/incubator/SynapseProposal', 'A'),
(83, 'Mozilla/4.0 (compatible; U; MSIE 9.0; WIndows NT 9.0; en-CA)', 'Spam', 'S'),
(91, '<a href="http://www.alexaboostup.com">Alexa Booster</a>', 'Spam', 'S'),
(93, 'HeyTell A3.0.8.346', 'Unknown', 'S'),
(94, 'RI Checker', 'Unknown', 'S'),
(95, 'PHP/5.3.19', 'http://php.net/', 'A'),
(97, 'Dillo/0.8.6-i18n-misc', 'http://www.dillo.org/ - Web browser, Unkown OS', 'S'),
(98, '"Mozilla/5.0"', 'Spam', 'S'),
(99, 'Mozilla/4.0 (compatible; MSIE8.0; Windows NT 6.0) .NET CLR 2.0.50727)', 'Unknown MSIE8.0 Instead of MSIE 8.0 (space) chinese', 'S'),
(100, 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/536.28.10 (KHTML, like Gecko) QuickLook/4.0', 'Unknown', 'S'),
(101, 'Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.7.6)', 'Browser Not recognized', 'A'),
(102, 'SiriusXM 2.2.0 (iPhone; iPhone OS 5.1; en_US)', 'completely unknown', 'A'),
(103, 'Mozilla/5.0 (PLAYSTATION 3 4.40) AppleWebKit/531.22.8 (KHTML, like Gecko)', 'Browser Not recognized', 'S'),
(104, 'http://www.checkprivacy.or.kr:6600/RS/PRIVACY_ENFAQ.jsp', 'Korea Internet', 'S'),
(105, 'Mozilla/5.0 (Windows; U; Windows NT 6.1; de-DE) AppleWebKit/533.4 (KHTML, like Gecko) Chrome/5.0.375.126 Chrome anonymized by Abelssoft 1281368432,gzip(gfe)', 'Spam', 'S'),
(106, 'Jigsaw/2.3.0-beta2', 'Spam', 'S'),
(107, 'HTTPClient/1.0 (2.3.3, ruby 1.9.3 (2013-02-21))', 'Spam', 'S'),
(110, 'YisouSpider', 'Spam', 'S'),
(111, 'YisouSpider', 'Spam', 'S'),
(112, 'Java/1.7.0_11', 'Java', 'A'),
(113, 'Java/1.6.0_39', 'Java', 'A'),
(114, 'Java/1.4.1_04', 'Java', 'A'),
(115, 'WebRingChecker/1.71 LWP/5.805', 'Unknown', 'A'),
(116, 'WebRingChecker/1.71 LWP/5.79', 'Unknown', 'A'),
(117, 'AppEngine-Google; (+http://code.google.com/appengine; appid: mehproxy)', 'Spam', 'S'),
(118, 'linkdex.com/v2.0', 'Commercial SEO', 'S'),
(119, 'http://www.americanexpress.com [amex:prodSearch] Java/1.7.0_09', 'Spam', 'S'),
(120, 'http://www.americanexpress.com [amex:prodSearch] Java/1.6.0_27', 'Spam', 'S'),
(121, 'Java/1.7.0_17', 'Java', 'S'),
(122, 'Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-US)', 'Spam', 'S'),
(123, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; fr-FR; rv:1.7.5) Gecko/20050620 Linspire Inc./1.0', 'Unknown', 'A'),
(124, 'Mozilla/5.0 (Unknown; Linux i686) AppleWebKit/534.34 (KHTML, like Gecko) FbxQmlTV Safari/534.34', 'Spam', 'S'),
(125, 'Mozilla/4.0 (compatible; MSIE 6.1; Windows XP)', 'Spam', 'S'),
(126, 'Mozilla/4.0 (compatible; msie 4.01; mac_powerpc)', 'Spam', 'S'),
(127, 'Mozilla/4.0 (compatible; MSIE 4.01; Mac_PowerPC)', 'Spam', 'S'),
(128, 'Mozilla/5.0 (compatible; http://alyze.info)', 'Alyze http://alyze.info est un outil en ligne permettant aux créateurs de site d''optimiser leurs pages pour un meilleur référencement. Les webmasters se voient également guidés pour une utilisation appropriée des technologies du Web.', 'A'),
(129, 'PEAR HTTP_Request class ( http://pear.php.net/ )', 'http://pear.php.net/package/HTTP_Request', 'A'),
(130, 'FisigBot/1.1(+http://www.fisig.com)', 'Spam', 'S'),
(133, 'crawler4j (http://code.google.com/p/crawler4j/)', 'http://code.google.com/p/crawler4j/', 'S');
