
-- --------------------------------------------------------

-- Contenu de la table `allmystats_crawler`
--

(1, NULL, 'Google Image', 'Googlebot-Image', 'http://images.google.com/', '', NULL),
(2, NULL, 'Google-Adsense', 'Mediapartners-Google', NULL, '', NULL),
(3, NULL, 'FeedFetcher-Google', 'FeedFetcher-Google', NULL, '', NULL),
(4, NULL, 'Google-Sitemaps', 'Google-Sitemaps', NULL, '', NULL),
(5, NULL, 'Google', 'Googlebot', NULL, '', NULL),
(6, NULL, 'Yahoo!', 'Yahoo! Slurp', NULL, '', NULL),
(7, NULL, 'Altavista', 'Scooter', 'http://www.altavista.com', 'Moteur de recherche', NULL),
(8, NULL, 'Gigablast', 'Gigabot', 'http://www.gigablast.com/spider.html', 'Moteur de recherche', NULL),
(9, NULL, 'Sogou', 'Sogou web spider', 'http://www.sogou.com/docs/help/webmasters.htm#07', 'Chinese Search Engine', NULL),
(10, NULL, 'Voila', 'VoilaBot', 'http://www.voila.com', '', NULL),
(11, NULL, 'MSN', 'msnbot', 'http://search.msn.com/msnbot.htm', '', NULL),
(12, NULL, 'entireweb', 'Speedy Spider', 'http://www.entireweb.com', 'Moteur de recherche', NULL),
(13, NULL, 'www.cuill.com', 'Twiceler', 'http://www.cuill.com/twiceler/robot.html', 'Moteur de recherche', NULL),
(14, NULL, 'www.super.info', 'superbot.com', 'http://www.super.info', 'Moteur de recherche', NULL),
(15, NULL, 'Exalead', 'Exabot', 'http://www.exalead.fr', 'Moteur de recherche', NULL),
(16, NULL, 'www.baidu.com', 'Baiduspider', 'http://www.baidu.com/search/spider_jp.html', 'Chinese Search Engine', NULL),
(17, NULL, 'soso.com', 'Sosoimagespider', 'http://www.soso.com', 'Chinese picture Search Engine', NULL),
(18, NULL, 'www.discoveryengine.com', 'discobot', 'http://www.discoveryengine.com/discobot.html', 'Discobot is the experimental web crawler', NULL),
(19, NULL, 'www.shopwiki.com', 'ShopWiki', 'http://www.shopwiki.com/wiki/Help:Bot', '', NULL),
(20, NULL, 'GnoZtiK', 'GnoZtiK bot', 'http://www.gnoztik.com/', 'Site pour optimiser le référencement', NULL),
(21, NULL, 'www.yandex.ru', 'Yandex', 'http://www.yandex.ru', 'Moteur de recherche Russe', NULL),
(22, NULL, 'Xenu Link', 'Xenu Link', 'http://www.google.fr/search?hl=fr&q=xenu&btnG=Rechercher&meta=lr%3Dlang_fr', 'Test des liens morts', NULL),
(23, NULL, 'libwww-perl', 'libwww-perl', 'http://search.cpan.org/dist/libwww-perl/', 'Attention, il peut chercher des failles', NULL),
(24, NULL, 'Alexa Web Search', 'ia_archiver', 'http://www.alexa.com', 'Statistiques sites', NULL),
(25, NULL, 'Whois Source', 'SurveyBot', 'http://www.whois.sc/info/webmasters/surveybot.html', 'www.whois.sc', NULL),
(26, NULL, 'ask', 'Ask Jeeves', 'http://fr.ask.com', 'Moteur de recherche', NULL),
(27, NULL, 'DMOZ', 'Robozilla', 'http://www.dmoz.org', 'Open Directory Project', NULL),
(28, NULL, 'Sqworm', 'Sqworm', NULL, 'No idea about this one', NULL),
(29, NULL, 'Microsoft', 'msnbot-media', 'http://search.msn.com/msnbot.htm', '', NULL),
(30, NULL, 'Larbin', 'larbin_2.6.3', 'http://larbin.sourceforge.net/index-eng.html', 'Multi-purpose web crawler', NULL),
(31, NULL, 'betaBot', 'betaBot', NULL, 'Pas d''info', NULL),
(32, NULL, 'www.scoutjet.com', 'ScoutJet', 'http://www.scoutjet.com', 'ScoutJet est le robot d\\''exploration du Web pour une nouvelle Silicon Valley moteur de recherche créé par les fondateurs de DMOZ et Topix.', NULL),
(33, NULL, 'gossamer-threads.com', 'Links SQL', 'http://gossamer-threads.com', '', NULL),
(34, NULL, 'HTTPConnect', 'HTTPConnect', '', 'Aspirateur de site', NULL),
(35, NULL, 'Heritrix', 'heritrix/2.0.0', 'http://crawler.archive.org', 'Internet Archive''s open-source', NULL),
(36, NULL, 'www.snap.com', 'Snapbot/1.0', 'http://www.snap.com', '', NULL),
(37, NULL, 'Commoncrawl', 'CCBot/1.0', 'http://www.commoncrawl.org/bot.html', '', NULL),
(38, NULL, 'HTMLParser', 'HTMLParser', 'http://htmlparser.sourceforge.net/', 'Extraction des liens d''une page web', NULL),
(39, NULL, 'Ichiro', 'Ichiro', 'http://help.goo.ne.jp/door/crawler.html', 'Chinese Search Engine', NULL),
(40, NULL, 'Nutch', 'nutch/Nutch', 'http://lucene.apache.org/nutch/bot.html', 'Open source project', NULL),
(41, NULL, 'FDSE robot', 'FDSE robot', NULL, '', NULL),
(42, NULL, 'RAYSPIDER/Nutch-0.9', 'RAYSPIDER/Nutch-0.9', NULL, 'I can''t find much info on this', NULL),
(43, NULL, 'Exooba', 'exooba crawler/0.5.1', 'http://www.exooba.com', 'exooba crawler for exooba search pre-alpha development', NULL),
(44, NULL, 'AdsBot-Google', 'AdsBot-Google', 'http://www.google.com/adsbot.html', 'AdWords', NULL),
(45, NULL, 'QEAVis', 'QEAVis agent/Nutch-0.9', 'http://nlp.uned.es/qeavis', NULL, NULL),
(46, NULL, 'Google', 'Google Keyword Tool', 'https://adwords.google.com/select/KeywordToolExternal', 'Générateur de mots clés', NULL),
(47, NULL, 'Exalead', 'NG/2.0', 'http://www.exalead.com/cgi/exalead', 'Moteur de recherche', NULL),
(48, NULL, ' ? Onetime Program ?', 'Onetime Program', NULL, NULL, NULL),
(49, NULL, 'page_verifier', 'page_verifier', 'http://www.securecomputing.com/goto/pv', NULL, NULL),
(50, NULL, 'Tipiweb/Nutch-0.9', 'Tipiweb/Nutch-0.9', NULL, 'Pas d''info', NULL),
(51, NULL, 'www.visvo.com', 'VisBot/2.0', 'http://www.visvo.com/bot.html', 'Petit moteur de recherche qui ne fonctionne pas bien.', NULL),
(52, NULL, 'www.rankiva.com', 'Rankivabot', 'http://www.rankiva.com', 'Rankiva is an online tool that ranks websites.', NULL),
(53, NULL, 'gossamer-threads.com', 'Links 2.0', 'http://gossamer-threads.com/scripts/links/', NULL, NULL),
(54, NULL, 'Java/1.6.0_10-beta', 'Java/1.6.0_10-beta', NULL, 'First Seen On: 24/05/2008', NULL),
(55, NULL, 'Scrubby', 'Scrubby', 'http://www.scrubtheweb.com/abs/meta-check.html', 'META Tag Analyzer', NULL),
(56, NULL, 'Python-urllib', 'Python-urllib', 'http://www.lib.uchicago.edu/keith/courses/python/class/7/', 'Phyton Module for fetching data across the World Wide Web', NULL),
(57, NULL, 'Cyberpatrol', 'CyberPatrol SiteCat Webbot', 'http://www.cyberpatrol.com/cyberpatrolcrawler.asp', 'Logiciel de contrôle parental', NULL),
(58, NULL, 'Flatlandindustries', 'flatlandbot/flatlandbot', 'http://www.flatlandindustries.com', 'Experimental Web Index', NULL),
(59, NULL, 'Metadatalabs', 'MLBot', 'http://www.metadatalabs.com/mlbot', NULL, NULL),
(60, NULL, 'kalooga', 'KaloogaBot', 'http://www.kalooga.com', 'Moteur de recherche', NULL),
(61, NULL, 'Grub', 'Grub/2.0', 'http://www.grub.org', NULL, NULL),
(62, NULL, 'Exalead', 'Exabot-Thumbnails', 'http://www.exalead.com', 'Exabot-Thumbnails ne genere des thumbnails que pour les urls crawlées par Exabot', NULL),
(63, NULL, 'Yahoo! Slurp China', 'Yahoo! Slurp China', 'http://misc.yahoo.com.cn/help.html', NULL, NULL),
(64, NULL, 'Yahoo!', 'BonEcho/2.0.0.4', NULL, NULL, NULL),
(65, NULL, 'Yahoo! DE', 'Yahoo! DE Slurp', 'http://help.yahoo.com/help/us/ysearch/slurp', NULL, NULL),
(66, NULL, 'DotBot', 'DotBot/1.0.1', 'http://www.dotnetdotcom.org', NULL, NULL),
(67, NULL, 'Amfibi\\''s web-crawling', 'Cabot/Nutch-0.9', 'http://www.amfibi.com/cabot/', 'Moteur de recherche', NULL),
(68, '', '', 'My Spider 1.0', '', 'No information available', ''),
(69, NULL, 'Acoon', 'Acoon-Robot 4.0.2.17', 'http://www.acoon.de', 'Moteur de recherche Allemand', NULL),
(70, NULL, 'BrightCloud', 'BrightCrawler', 'http://www.brightcloud.com/brightcrawler.asp', NULL, NULL),
(71, NULL, 'Crawl Annu', 'Crawl Annu', NULL, 'Inconnu', NULL),
(72, NULL, 'Eurobot/Nutch', 'Eurobot/Nutch-1.0-dev', NULL, 'Inconnu', NULL),
(73, NULL, 'www.snap.com', 'SnapPreviewBot', 'http://www.snap.com', 'Snap Firefox Search Plugin', NULL),
(74, NULL, 'Yeti', 'Yeti/1.0', 'http://help.naver.com/robots/', 'chinese bot', NULL),
(75, NULL, 'Amfibi''s web-crawling', 'Cabot/Nutch-1.0-dev', 'http://www.amfibi.com/cabot/', 'Amfibi''s web-crawling robot', NULL),
(76, NULL, 'Microsoft isrc-bot', 'MSR-ISRCCrawler', NULL, '', NULL),
(77, NULL, 'panscient.com', 'panscient.com', '', 'Panscient explore le Web et recueille des informations sur les personnes et les entreprises pour des applications de recherche', NULL),
(78, NULL, 'therarestwords', 'TheRarestParser/0.2a', 'http://therarestwords.com', 'The Rarest Words - Linguistic experiment crawler via Amazon Web Services', NULL),
(79, NULL, 'www.wauuu.com', 'wauuu engine/Wauuu 0.1', 'http://www.wauuu.com', NULL, NULL),
(80, NULL, 'Microsoft Corporation', 'MSNPTC/Test', 'http://msn.com', 'No information available', NULL),
(81, NULL, 'OpenAcoon', 'OpenAcoon v4.0.3', 'http://www.openacoon.de', NULL, NULL),
(82, NULL, 'compatible; Indy Library', 'compatible; Indy Library', NULL, 'Pas d''info', NULL),
(83, NULL, 'holmes/3.12', 'holmes/3.12', 'http://morfeo.centrum.cz/bot', 'Pas d''info', NULL),
(84, NULL, 'OpenAcoon', 'OpenAcoon v4.0.5', 'http://www.openacoon.de', NULL, NULL),
(85, NULL, '', 'shelob v1.0', '', 'Bad bot', NULL),
(86, NULL, 'NetWhat', 'NetWhatCrawler/0.06-dev', 'http://www.netwhat.com', 'Moteur de recherche', NULL),
(87, NULL, 'Exooba', 'exooba crawler/exooba', 'http://www.exooba.com', 'exooba crawler for exooba search pre-alpha development', NULL),
(88, NULL, 'Exooba', 'exooba/exooba', 'http://www.exooba.com', 'exooba crawler for exooba search pre-alpha development', NULL),
(89, NULL, 'Thumbshots', 'thumbshots-de-bot', 'http://www.thumbshots.de', NULL, NULL),
(90, NULL, 'Moreover', 'Moreoverbot/5.00', 'http://www.moreover.com', NULL, NULL),
(91, NULL, 'MSIECrawler', 'MSIECrawler', NULL, 'MSIECrawler is not a true web robot. It is usually to be found in site logs if someone bookmarks a page whilst offline. Internet Explorer will then download the page and all links related to it, including links, images, JavaScript and Style sheets, when t', NULL),
(92, NULL, 'www.myengines.org', 'MyEngines-Bot', 'http://www.myengines.org', NULL, NULL),
(93, NULL, 'NetEase', 'YodaoBot/1.0', 'http://www.163.com/', 'NetEase is known for its popular Chinese portal 163.com. It was using Google as its search engine till the middle of 2007, when it decided to replace it by yodao, its own search engine.', NULL),
(94, NULL, 'Microsoft', 'MSRBOT', 'http://research.microsoft.com/research/sv/msrbot/', 'We are using the MSRBot web crawler to collect data from the web for further study.', NULL),
(95, NULL, 'quickengines.com', 'Jeanie_2008_bot/3.2', 'http://www.quickengines.com', NULL, NULL),
(96, NULL, 'PhpDig.net', 'PhpDig/1.8.0', 'http://www.phpdig.net/robot.php', NULL, NULL),
(97, NULL, 'Nokia find.mobi', 'Nokia6300/2.0', 'http://find.mobi/bot.html', NULL, NULL),
(98, NULL, 'freedownloadmanager.org', 'FDM 2.x', 'http://www.freedownloadmanager.org/', 'Free Download Manager (FDM) download accelerator', NULL),
(99, NULL, 'GoogleToolbar', 'GoogleToolbar 2.0.111-big', NULL, NULL, NULL),
(100, NULL, 'Java/1.6.0_06', 'Java/1.6.0_06', NULL, NULL, NULL),
(101, NULL, 'Touche', 'Touche', 'http://www.touche.com.ve/', 'Search engine', NULL),
(102, NULL, 'www.semager.de', 'Semager/1.2', 'http://www.semager.de/blog/semager-bots/', NULL, NULL),
(103, NULL, 'www.sigram.com', 'Sigram/Nutch-1.0-dev', 'http://www.sigram.com/bot.html', 'Test agent for Nutch development', NULL),
(104, NULL, 'WebDataCentre.com', 'WebDataCentreBot/1.0', 'http://WebDataCentre.com/', 'Projet de recherche conduit par une petite équipe de chercheurs de différentes régions du monde.', NULL),
(105, NULL, 'Sqwidge', 'SqwidgeBot a0.3.23', 'http://www.sqwidge.com/bot/', 'Développement moteur de recherche', NULL),
(106, NULL, 'setooz.com', 'OOZBOT/0.17', 'http://www.setooz.com/oozbot.html', 'Moteur de recherche', NULL),
(107, NULL, 'rulinki.ru project', 'rulinki.ru project', '', 'Non indentifié', NULL),
(108, '', 'MailWalker', 'MailWalker', 'http://www.websynaptics.com/solutions.html', 'Extracteur d''emails', ''),
(109, '', 'Sogou', 'Sogou Pic Spider/3.0', 'http://www.sogou.com/docs/help/webmasters.htm#07', 'Chinese picture Search Engine', ''),
(110, '', 'Wikiwix', 'wikiwix-bot-3.0', 'http://www.wikiwix.com/', 'Wikipedia articles search engine', ''),
(111, '', 'Jakarta Commons-HttpClient/3.0.1', 'Jakarta Commons-HttpClient/3.0.1', 'http://hc.apache.org/httpclient-3.x/', '', ''),
(112, '', 'Yahoo', 'Yahoo-MMCrawler', 'http://www.robotstxt.org/wc/exclusion.html#robotstxt', 'Recherche d''images', ''),
(113, '', 'www.picsearch.com', 'psbot/0.1', 'http://www.picsearch.com/bot.html', 'PicSearch index des images à  partir du Web.', ''),
(114, '', 'Yahoo!-AdCrawler', 'Yahoo!-AdCrawler', ' http://help.yahoo.com/yahoo_adcrawler', '', ''),
(115, '', 'Reedbusiness', 'CatchBot/1.0', 'http://www.catchbot.com', 'Reed Business Information propose de l''information et de l''espace de communication B to B à  travers ses 3 métiers : presse, édition et formation.', ''),
(116, '', 'hrinktheweb.com', 'ShrinkTheWeb.com Crawler v1.0', 'http://www.shrinktheweb.com', 'Miniature en image de votre site (thumbnail).', ''),
(117, '', 'WorldSearch', 'Yanga WorldSearch Bot v1.1', 'http://www.yanga.co.uk', 'Moteur de recherche', ''),
(118, '', 'Guruji', 'GurujiBot/1.0', 'http://www.guruji.com/en/WebmasterFAQ.html', 'Moteur de recherche', ''),
(119, '', 'Turnitin', 'TurnitinBot/2.1', 'http://www.turnitin.com/robot/crawlerinfo.html', 'Site permettant aux professeurs de voir si les élèves ont copié des phrases sur Internet.', ''),
(120, '', 'FollowSite', 'FollowSite Bot', 'http://www.followsite.com/bot.html', 'Votre site web est important pour un (ou plusieurs) de nos utilisateurs et a été ajouté à  FollowSite. Nous allons maintenant surveiller votre site et lui notifier quand il est mis à jour.', ''),
(121, '', 'Sapphire Web Crawler using Nutch', 'SapphireWebCrawler/Nutch-1.0-dev', 'http://boston.lti.cs.cmu.edu/crawler/', 'Le projet est la création d\\''une base de données de 1 milliard de pages web en 10 langues qui seront utilisées à  des fins de recherche par les scientifiques du monde entier. Le projet est supervisé par le professeur Jamie Callan.', ''),
(122, '', 'Sapphire Web Crawler using Nutch', 'SapphireWebCrawler/1.0', 'http://boston.lti.cs.cmu.edu/crawler', 'Le projet est la création d\\''une base de données de 1 milliard de pages web en 10 langues qui seront utilisées à  des fins de recherche par les scientifiques du monde entier. Le projet est supervisé par le professeur Jamie Callan.', ''),
(123, '', 'dotnetdotcom', 'DotBot/1.1', 'http://www.dotnetdotcom.org', '', ''),
(124, '', 'dontbuylists.com', 'DBLBot/1.0', 'http://www.dontbuylists.com', '', ''),
(125, '', 'askpeter', 'askpeter_bot_5.0', 'http://www.askpeter.info', 'Moteur de recherche', ''),
(126, '', 'gingersoftware.com', 'GingerCrawler', 'http://www.gingersoftware.com/crawler_agent.htm', 'Language Assistant for Dyslexics', ''),
(127, '', 'kilomonkey.com', 'kmky-not-a-bot/0.2', 'http://www.kilomonkey.com/notabot.txt', 'Pas d''infos', ''),
(128, '', 'Flatland Industries Web Spider', 'flatlandbot/baypup', 'http://www.flatlandindustries.com/flatlandbot', '', ''),
(129, '', 'first-search.com', 'FirstSearchBot/1.0', 'http://www.first-search.com', 'Moteur de recherche', ''),
(130, '', 'gais.cs.ccu.edu.tw', 'Gaisbot/3.0', 'http://gais.cs.ccu.edu.tw/robot.php', 'Développement moteur de recherche', ''),
(131, '', 'apercite.fr', 'Apercite', 'http://www.apercite.fr/robot/index.html', 'Miniature en image de votre site.', ''),
(132, '', 'askpeter.info', 'askpeter_bot/5.0', 'http://www.askpeter.info', 'Moteur de recherche', ''),
(133, '', 'bibnum.bnf.fr', 'bnf.fr_bot', 'http://bibnum.bnf.fr/robot/bnf.html', 'Vous avez été renvoyé à cette page car votre site est actuellement collecté automatiquement par la Bibliothèque nationale de France (BnF).', ''),
(134, '', 'Nokia', 'Nokia6682/2.0', 'http://help.yahoo.com/help/us/ysearch/crawling/crawling-01.html', '', ''),
(135, '', 'Nokia', 'Nokia6680/1.0', '', '', ''),
(136, '', 'SimilarPages Nutch Crawler', 'SimilarPages/Nutch-1.0-dev', 'http://www.similarpages.com', 'Pas d\\''infos à  ce jour', ''),
(137, '', '', 'digiSelf crawler/Nutch-1.0-dev', '', 'Pas d\\''infos à  ce jour', ''),
(138, '', 'Flatland Industries Web Spider', 'flatlandbot/allspark', 'http://www.flatlandindustries.com/flatlandbot', '', ''),
(139, '', 'Robotgenius.net', 'robotgenius', 'http://robotgenius.net', '', ''),
(140, '', 'www.kosmix.com', 'voyager/2.0', 'http://www.kosmix.com/crawler.html', 'Il récupère des documents sur le Web pour construire l\\''indice du moteur de recherche Kosmix', ''),
(141, '', 'yacy.net', 'yacybot', 'http://yacy.net/bot.html', 'yacybot est le useragent du logiciel YaCy, qui est une approche pour construire un réseau de peer-to-Peer basé websearch-moteur.', ''),
(142, '', 'ODP link checker', 'pmoz.info ODP link checker', 'http://pmoz.info/doc/botinfo.htm', 'Vérifie des liens de l\\''annuaire Dmoz Open Directory Project', ''),
(143, '', 'OrangeBot-Mobile', 'OrangeBot-Mobile', 'http://www.orange.com/en_EN/', 'Orange France robot for mobiles', ''),
(144, '', 'afholderbach.net', 'ecoNet', 'http://www.eco.afholderbach.net', '', ''),
(145, '', 'LinguaSeek', 'LinguaSeek', 'http://www.linguaseek.com', 'Moteur de recherche', ''),
(146, '', '', 'SheenBot', '', '', ''),
(147, '', '', 'My Spider 1.0', '', '', ''),
(148, '', 'W3C Validator', 'W3C_Validator', 'http://validator.w3.org/', 'Test des pages web à  la norme W3C', ''),
(149, '', 'W3C CSS Validator', 'W3C_CSS_Validator', 'http://jigsaw.w3.org/css-validator', 'Test W3C des feuilles CSS', ''),
(150, '', 'GSiteCrawler', 'GSiteCrawler', 'http://gsitecrawler.com/', 'Bot du logiciel pour construire le SiteMap - gsitecrawler', ''),
(151, '', 'PHPCrawl', 'PHPCrawl', '', 'Pas d''information', ''),
(152, '', 'Sosospider', 'Sosospider', 'http://help.soso.com/webspider.htm', '', ''),
(153, '', 'woozweb-monitoring', 'woozweb-monitoring', 'http://www.woozweb.com', 'observatoire du web et monitoring gratuit', ''),
(154, '', 'Tagoobot', 'Tagoobot/3.0', 'http://www.tagoo.ru', 'Exclusivement russe', ''),
(155, '', '50.nu/0.01', '50.nu/0.01', 'http://50.nu/bot.html', 'Si vous lisez ces lignes, il est probable que quelqu\\''un a ajouté votre site à notre base de données. Cela signifie qu\\''ils seront mis au courant par email ou par RSS à  chaque fois votre site est mis à  jour.', ''),
(156, '', 'youdao.com', 'YoudaoBot/1.0', 'http://www.youdao.com/help/webmaster/spider/', 'Exclusivement chinois', ''),
(157, '', '80legs.com', '008/0.83', 'http://www.80legs.com/spider.html', '', ''),
(158, '', 'Askpeter', 'askpeter_bot/5.1', 'http://www.askpeter.info', 'Moteur de recherche', ''),
(159, '', 'Who.is', 'Who.is Bot', 'http://who.is/', 'Information sur les noms de domaine', ''),
(160, '', 'Sogou', 'Sogou-Test-Spider/4.0', 'http://www.sogou.com/', 'Moteur de recherche chinois', ''),
(161, '', 'linguee.com', 'Linguee Bot', 'http://www.linguee.comlinguee.com', 'Linguee is more than a German-English dictionary', ''),
(162, '', 'seexie.com', 'seexie.com_bot', 'http://www.seexie.com', 'Search engine', ''),
(163, '', 'LinkStar', 'LinkStar Research', 'http://linkstar.com/', 'Hébergeur qui cherche à se faire des liens via les stats ?', ''),
(164, '', 'parchmenthill.com', 'ParchBot/1.0', 'http://www.parchmenthill.com/search.htm', 'Nous travaillons sur un projet spécial qui peut être décrit comme un moteur de recherche de domaine', ''),
(165, '', 'www.majestic12.co.uk', 'MJ12bot', 'http://www.majestic12.co.uk/bot.php?+', 'Ce projet porte sur la création d\\''un moteur de recherche World Wide Web reposant sur des concepts de distribution de la charge de travail', ''),
(166, '', 'Tasapspider', 'Tasapspider', 'http://www.tasap.com', 'Moteur de recherche', ''),
(167, '', 'chenli.com.cn', 'Chen Li/Nutch-1.0', 'http://chenli.com.cn', '', ''),
(168, '', 'www.seoprofiler.com', 'spbot', 'http://www.seoprofiler.com/bot/', 'A mettre dans le robots.txt, c''est un spam pour un logiciel', ''),
(169, '', 'www.puritysearch.net', 'Purebot', 'http://www.puritysearch.net', 'Sorte d\\''annuaire sans intéret. A mettre dans le robots.txt', ''),
(170, '', 'www.perdu.com', 'RssFetcherBot', 'http://www.perdu.com', 'Site Clin d''oeil', ''),
(171, '', 'www.aihit.com', 'aiHitBot', 'http://www.aihit.com', 'Spam. A metrre dans robots.txt', ''),
(172, '', 'www.rodeur.fr', 'RodeurBot', 'http://www.rodeur.fr/rodeurbot.html', 'Petit annuaire français, sympa', ''),
(173, '', 'www.cizilla.com', 'Cizilla-', 'http://www.cizilla.com', 'Moteur de recherche', ''),
(174, '', 'Aport', 'AportCatalogRobot', 'http://www.aport.ru/', 'Russian search engine', ''),
(175, '', 'Twenga', 'TwengaBot', 'http://www.twenga.com/bot.html', 'Guide d''achat', ''),
(176, '', 'MaMa CyBer', 'MaMa CyBer', '', 'TODO, àvoir ce que c''est', ''),
(177, '', 'Bing', 'bingbot', 'http://www.bing.com/bingbot.htm', '', ''),
(178, '', 'www.cfilt.iitb.ac.in', 'IITB-CFILT-Bot', 'http://www.cfilt.iitb.ac.in/', 'This is the crawler of IIT Bombay, India. The data will be used for research purposes', ''),
(181, '', 'Google ?', 'kw-lp-suggest', '', 'Todo verifie --> Bot Adwords or Analytics ?', ''),
(182, '', 'www.cityreview.org', 'Cityreview Robot', 'http://www.cityreview.org/crawler/', '', ''),
(183, '', 'Google Web Preview', 'Google Web Preview', '', 'Génération des screenshots Google', ''),
(184, '', 'www.aport.ru', 'AportWorm', 'http://www.aport.ru/help', 'Russian search engine', ''),
(185, '', 'aport.ru', 'AportCatalogRobot', 'http://www.aport.ru/', 'Russian search engine', '');
