<h2>Catégorie <?php echo strtolower($view->cat_name); ?></h2>
<hr />
<a class="lead_btn" href="#idlead_form">Demander un devis <?php echo strtolower($view->cat_name); ?> gratuit&nbsp;
<span class="arrow">→</span></a>
<hr />
<h3>Contacter directement un artisan :</h3>
<?php foreach ($view->actors as $region => $actors) { ?>
<h3>Artisans <?php echo strtolower($view->cat_name); ?> en <?php echo ucfirst($region); ?></h3>
<ul>
    <?php foreach ($actors as $a) { ?>
    <li>
        <a href="actor-<?php echo $a['slug']; ?>-<?php echo $a['id']; ?>">
            <?php echo $a['name']; ?>
        </a>
    </li>
    <?php } ?>
</ul>
<?php }?>
