<?php
if (empty($view->articles)) {
    ?>
    <div class="postcontent">
    Aucun article trouvé.
    </div>
    <?php
}
if (!empty($view->has_top_article)) {
    $art = $view->articles[0];
    ?>
        <a href="art-<?php echo $art->url; ?>-<?php echo $art->id; ?>">
            <div class="top_art header_art_img">
            <div class="read_next">Lire la suite</div>
            <?= $art->get_top_image(); ?>
            <header class="top_art_header">
                <div class="postDate">
                    <span itemprop="datePublished" title="<?php echo str_replace(' ', 'T', $art->pubdate); ?>">
                        <div><?= $art->day ." ". $art->month .' '. $art->year; ?></div>
                <?php
                    if($art->ecart < 0){
                        $jour = floor(-$art->ecart/(3600*24));
                        $heure = floor((-$art->ecart-$jour*3600*24)/3600);
                        $minutes = floor((-$art->ecart-$jour*3600*24-$heure*3600)/60);
                        echo "<span style=\"color:red;\">(".$jour."j ".$heure."h ".$minutes."mn)</span>";
                    }
                ?>
                    </span>
                </div>
                <div class="postTitle" itemprop="name">
                    <?php echo stripslashes($art->titre); ?>
                </div>
            </header>
            </div>
            <div class="fake_top"></div>
        </a>
    <?php
}
$i = 0;
foreach ($view->articles as $art) {
    ?>
    <article class="post <?php echo ($i % 2 == 0) ? "odd" : "even"; ?>" itemprop='blogPost' itemscope='itemscope' itemtype='http://schema.org/BlogPosting'>
        <meta content='<?php echo $art->id; ?>' itemprop='postId'/>
        <meta itemprop="inLanguage" content="fr-FR"/>
        <header>
            <div class="header_art_img">
                <a href="art-<?php echo $art->url; ?>-<?php echo $art->id; ?>">
                    <?= $art->get_top_image(); ?>
                </a>
            </div>
            <div class="postDate">
                <span itemprop='datePublished' title='<?php echo str_replace(' ', 'T', $art->pubdate); ?>'>
                    <div><?= $art->day ." ". $art->month .' '. $art->year; ?></div>
            <?php
                if($art->ecart < 0){
                    $jour = floor(-$art->ecart/(3600*24));
                    $heure = floor((-$art->ecart-$jour*3600*24)/3600);
                    $minutes = floor((-$art->ecart-$jour*3600*24-$heure*3600)/60);
                    echo "<span style=\"color:red;\">(".$jour."j ".$heure."h ".$minutes."mn)</span>";
                }
            ?>
                </span>
            </div>
            <div class="postTitle" itemprop='name'>
                <a href="art-<?php echo $art->url; ?>-<?php echo $art->id; ?>">
                    <?php echo stripslashes($art->titre); ?>
                </a>
            </div>
        </header>
        <div class="mainpost">
            <div class="postcontent" itemprop='description articleBody'>
                <?= $art->art_abstract(); ?>
            </div>
        </div>
        <footer class="short_com comconteneur">
            <?php
            if(!empty($_SESSION['ok']) && $_SESSION['ok'] == 1){
                echo " - <a class=\"comlink\" href=\"article_edit-".$art->id."\">Editer</a> -
                <a class=\"comlink\" href=\"article_delete-".$art->id."\">Supprimer</a><br/>";
            }
            ?>
        </footer>
        <hr/>
    </article>
    <?php
} ?>
<div class="clear"></div>
<div>
    <?php
    $page = (!empty($_GET['page'])) ? $_GET['page'] : 0;
    if (!empty($view->nb_pages)) {
        $nb_pages = $view->nb_pages;
        $suiv = ($nb_pages > 1 && $page != $nb_pages);
        $prec = ($nb_pages > 1 && !empty($page) && $page > 0);
        $year = (!empty($_GET['year'])) ? '-'.$_GET['year'] : '';
        $month = (!empty($_GET['month'])) ? '-'.$_GET['month'] : '';
        if (!empty($view->std_page_link)) {
            $lien_base = $view->std_page_link;
            $lien_base_home = $view->std_page_link;
        } else {
            $lien_base = "archive".$month.$year;
            $lien_base_home = "/";
        }
        if($prec){
            if ($page == 1) {
                $lien = $lien_base_home; //home page = first page
            } else {
                $lien = $lien_base."-page-".($page-1);
            }
            ?>
            <a href="<?= $lien ?>">
                <div class="main page_link even">
                    <span class="p_art small">Next</span>
                </div>
            </a>
            <?php
        }
        if($suiv){
            $lien = $lien_base."-page-".($page+1);
            ?>
            <a href="<?= $lien ?>">
                <div class="main page_link odd">
                    <span class="p_art small">Previous</span>
                </div>
            </a>
            <?php
        }
    }
    ?>
</div>
