<?php
foreach ($view->articles as $art) {
	?>
	<article class="post" itemprop='blogPost' itemscope='itemscope' itemtype='http://schema.org/BlogPosting'>
        <meta content='<?php echo $art->id; ?>' itemprop='postId'/>
        <meta itemprop="inLanguage" content="fr-FR"/>
	    <header>
		<span class="categorie">
			<a href="cat-<?php echo $art->category->slug; ?>-<?php echo $art->category->id; ?>">
                <?php echo $art->category->titre; ?>
            </a>
		</span>
		<h2 class="postTitle" itemprop='name'>
			<a href="art-<?php echo $art->url; ?>-<?php echo $art->id; ?>">
				<?php echo stripslashes($art->titre); ?>
			</a>
		</h2>
	    </header>
		<br/><br/>
		<div class="mainpost">
			<div class="postcontent" itemprop='description articleBody'>
				<?php echo stripslashes(
						   str_replace('</br>', '<br />', $art->texte)); ?>
				<br/><br/>
			</div>
		</div>
		<footer class="comconteneur">
<?php /*            <a class="like_link" href="<?php echo $art->id; ?>">
               J'aime (<span id="likes-<?php echo $art->id; ?>"><?php echo $art->nb_likes; ?></span>)
            </a>
            -
			<?php */
            if(!$art->closed_com){
                ?>
                <a class="comlink" href="art-<?php echo $art->url; ?>-<?php echo $art->id; ?>#postcom">
                    Commenter
                </a>
                 - 
            <?php
            }
            ?>
            <a href="art-<?php echo $art->url; ?>-<?php echo $art->id; ?>">
                Lire les commentaires (<?php echo $art->nb_comment; ?>)
            </a>
            <?php
			if(!empty($_SESSION['ok']) && $_SESSION['ok'] == 1){
				echo " - <a class=\"comlink\" href=\"article_edit-".$art->id."\">Editer</a> - 
				<a class=\"comlink\" href=\"article_delete-".$art->id."\">Supprimer</a><br/>";
			}
			?>
            <span class="postDate">
            <?php
                if($art->ecart < 0){
                    $jour = floor(-$art->ecart/(3600*24));
                    $heure = floor((-$art->ecart-$jour*3600*24)/3600);
                    $minutes = floor((-$art->ecart-$jour*3600*24-$heure*3600)/60);
                    echo "<span style=\"color:red;\"> Cet article sera publié dans ".$jour." jours ".$heure." heures et ".$minutes." minutes.</span><br/>";
                }
            ?>
                Écrit le <span itemprop='datePublished' title='<?php echo str_replace(' ', 'T', $art->pubdate); ?>'><?php echo $art->post_date; ?></span>
                par <span itemprop='author' itemscope='itemscope' itemtype='http://schema.org/Person'>
                    <meta content='http://www.melmelboo.fr/about' itemprop='url'/>
                    <a href='http://www.melmelboo.fr/about' rel='author' title='author profile'>
                        <span itemprop='name'><?php echo stripslashes($art->auteur); ?></span>
                    </a>
                </span>
            </span>
		</footer>
		<br/>
	</article>
	<br/>
	<hr/>
	<?php
} ?>
<div>
	<?php
    $page = (!empty($_GET['page'])) ? $_GET['page'] : 0;
    $nb_pages = $view->nb_pages;
	$suiv = ($nb_pages > 1 && $page != $nb_pages);
	$prec = ($nb_pages > 1 && !empty($page) && $page > 0);
    $year = (!empty($_GET['year'])) ? '-'.$_GET['year'] : '';
    $month = (!empty($_GET['month'])) ? '-'.$_GET['month'] : '';
    if (!empty($view->std_page_link)) {
        $lien_base = $view->std_page_link;
        $lien_base_home = $view->std_page_link;
    } else {
        $lien_base = "archive".$month.$year;
        $lien_base_home = "/";
    }
	if($prec){
        if ($page == 1) {
            $lien = $lien_base_home; //home page = first page
        } else {
    		$lien = $lien_base."-page-".($page-1);
        }
		echo '<span style="float:left;" class="page_link"><a href="'.$lien.'"><span class="arrow">←</span> NEWER</a></span>';
	}
	if($suiv){
		$lien = $lien_base."-page-".($page+1);
		echo '<span style="float:right;" class="page_link"><a href="'.$lien.'">OLDER <span class="arrow">→</span></a></span>';
	}
	?>
</div>
