<div style="clear: left;"></div>
<hr />

<div class="menuBlock">
    <div class="menuTitle">Liens</div>
    <ul class="ulmenuV">
        <li><a href="http://www.baudouin.fr/">Baudoin Photographer</a></li>
        <li><a href="http://www.theselby.com/">The Selby</a></li>
        <li><a href="http://www.vertcerise.com/">Vert Cerise</a></li> 
        <li><a href="http://karlascloset.blogspot.com/">Klaras's closet</a> </li>
        <li><a href="http://thestylishwanderer.blogspot.com/">The Stylish Wanderer</a> </li>
        <li><a href="http://www.taghrid.cc/">Taghrid.cc</a> </li>
        <li><a href="http://freelancersfashion.blogspot.com/">The Freelancer's Fashionblog</a> </li>	
        <li><a href="http://www.thecherryblossomgirl.com/">The cherry blossom girl</a> </li>
        <li><a href="http://www.misspandora.fr/">Pandora</a> </li>
        <li><a href="http://www.etpourquoipascoline.fr/">Et pourquoi pas Coline</a> </li>
        <li><a href="http://www.leblogdebetty.com/">Le blog deBetty</a> </li>
        <li><a href="http://www.leblogdelamechante.fr/">Eleonore Bridge</a> </li>
        <li><a href="http://margauxmotin.typepad.fr/margaux_motin/">Margaux Motin</a> </li>
    </ul>
</div>
