<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title>Voguer sur la vague et divaguer<?php echo (!empty($layout->title)) ? " - " . $layout->title : ""; ?></title>
        <meta name="description" content="<?php echo (!empty($layout->description)) ? $layout->description : "Le blog de Melmelboo !"; ?>" /> 
        <meta name="keywords" content="blog, melmelboo, frippes, ecolo, ecologie, recyclage, naturel, astuces, bricolage, truc, bloubiboulga<?php echo (!empty($layout->keywords)) ? implode(",", $layout->keywords) : ""; ?>" /> 
        <link href="/CSS/default.css" rel="stylesheet" type="text/css" media="screen" />
        <script type="text/javascript" src="/js/jquery.js"></script>
        <script type="text/javascript" src="/js/common.js"></script>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" type="text/css" href="/tools/shadowbox/shadowbox.css">
        <?php if (!empty($layout->canonical)) { ?>
        <link rel="canonical" href="<?php echo $layout->canonical; ?>"/>
        <?php } ?>
        <script type="text/javascript" src="/tools/shadowbox/shadowbox.js"></script>
        <script type="text/javascript">
            Shadowbox.init();
            $(function(){
                $(".postcontent img").each(function(index){
                    $(this).wrap('<a href="'+$(this).attr("src")+'" title="'+$(this).attr("alt")+'" rel="shadowbox[Gallerie]" />');
                });
            });
        </script>
        <link href='http://fonts.googleapis.com/css?family=Anton' rel='stylesheet' type='text/css'>
    </head> 
    <body>
        <div id="conteneur" itemscope='itemscope' itemtype='http://schema.org/Blog'>
            <meta content='Voguer sur la vague et divaguer' itemprop='name'/>
            <header>
                <nav class="main_nav">
                    <a href="/">HOME</a> / 
                    <a href="/diy">DIY</a> / 
                    <a href="/about">ABOUT</a> / 
                    <a href="/contact">CONTACT</a>
                </nav>
                <div id="header" onclick="location.href='/'">Melmelboo</div>
            </header>
            <div id="main">
                <div id="contenu">
                    <?php if (!empty($_speedmsg)) { ?>
                        <p>
                            <?php foreach ($_speedmsg as $msg) {
                                echo $msg."<br />";
                            } ?>
                        </p>
                    <?php } ?>
                    <?php echo $_view_str; ?>
                </div>
                <aside>
                    <div class="menuBlock">
                        <a href="/about">
                            <img style="width:237px;" src="/images/Moi.png" alt="À propos" />
                        </a>
                    </div>
                    <hr />
                    <?php echo $_widgets['last_art']; ?>
                    <nav id="menuBlockRight">
                        <?php echo $_widgets['categories']; ?>
                    </nav>
                    <nav id="menuBlockLeft">
                        <?php echo $_widgets['archives']; ?>
                    </nav>
                    <?php echo $_widgets['links']; ?>
                </aside>
            </div>
            <footer id="footer">
                <a href="/admin">- Admin -</a>
            </footer>
        </div>
    </body> 
</html> 
<?php
$Racine_abs = str_replace($_SERVER['PHP_SELF'],"",$_SERVER['SCRIPT_FILENAME']);
$nom_page=$_SERVER['REQUEST_URI'];
require $Racine_abs.'/allmystats/visiteur.php';
?> 
