<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title>Voguer sur la vague et divaguer<?php echo (!empty($layout->title)) ? " - " . $layout->title : ""; ?></title>
        <meta name="description" content="<?php echo (!empty($layout->description)) ? $layout->description : "Le blog de Melmelboo !"; ?>" /> 
        <meta name="keywords" content="blog, melmelboo, frippes, ecolo, ecologie, recyclage, naturel, astuces, bricolage, truc, bloubiboulga<?php echo (!empty($layout->keywords)) ? implode(",", $layout->keywords) : ""; ?>" /> 
        <link href="CSS/default.css" rel="stylesheet" type="text/css" media="screen" />
        <script type="text/javascript" src="js/jquery.js"></script>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" type="text/css" href="tools/shadowbox/shadowbox.css">
        <script type="text/javascript" src="tools/shadowbox/shadowbox.js"></script>
        <script type="text/javascript">
            Shadowbox.init();
            $(function(){
                $(".postcontent img").each(function(index){
                    $(this).wrap('<a href="'+$(this).attr("src")+'" title="'+$(this).attr("alt")+'" rel="shadowbox[Gallerie]" />');
                });
            });
        </script>
        <script type="text/javascript">
            <?php echo (!empty($fm_javascript)) ? $fm_javascript : ""; ?>
        </script>
        <link href='http://fonts.googleapis.com/css?family=Anton' rel='stylesheet' type='text/css'>
    </head> 
    <body>
        <div id="conteneur">
            <div id="menuH">
                <a href="/">HOME</a> / 
                <a href="/about">ABOUT</a> / 
                <a href="/contact">CONTACT</a>
            </div>
            <div id="header" onclick="location.href='http://www.melmelboo.fr'">Melmelboo</div>
            <div id="main">
                <div id="contenu">
                    <?php echo $_view_str; ?>
                </div>
                <div id="menuV">
                    <?php echo $_widgets['vertical_menu']; ?>
                    <?php require_once("modules/menuVertical/content.php"); ?>
                </div>
            </div>
            <div id="footer">
                <a href="/admin">- Admin -</a>
            </div>
        </div>
    </body> 
</html> 
<?php
$Racine_abs = str_replace($_SERVER['PHP_SELF'],"",$_SERVER['SCRIPT_FILENAME']);
$nom_page=$_SERVER['REQUEST_URI'];
require $Racine_abs.'/allmystats/visiteur.php';
?> 
