<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="p:domain_verify" content="1db92b33da4d2903d1645fd9d68efcf8" />
        <title>Melmelboo<?php echo (!empty($layout->title)) ? " - " . $layout->title : ""; ?></title>
        <meta name="description" content="<?php echo (!empty($layout->description)) ? $layout->description : "Le blog de Melmelboo !"; ?>" /> 
        <meta name="keywords" content="blog, melmelboo, frippes, ecolo, ecologie, recyclage, naturel, astuces, bricolage, truc, bloubiboulga<?php echo (!empty($layout->keywords)) ? implode(",", $layout->keywords) : ""; ?>" /> 
        <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,200,100,500,600,700' rel='stylesheet' type='text/css'>
        <link href="/CSS/default.css" rel="stylesheet" type="text/css" media="screen" />
        <script type="text/javascript" src="/js/jquery.js"></script>
        <script type="text/javascript" src="/js/common.js"></script>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" type="text/css" href="/tools/shadowbox/shadowbox.css">
        <?php if (!empty($layout->canonical)) { ?>
        <link rel="canonical" href="<?php echo $layout->canonical; ?>"/>
        <?php } ?>
        <script type="text/javascript" src="/tools/shadowbox/shadowbox.js"></script>
        <script type="text/javascript">
            Shadowbox.init();
            $(function(){
                $(".postcontent img").each(function(index){
                    $(this).wrap('<a href="'+$(this).attr("src")+'" title="'+$(this).attr("alt")+'" rel="shadowbox[Gallerie]" />');
                });
            });
        </script>
        <link href='http://fonts.googleapis.com/css?family=Anton' rel='stylesheet' type='text/css'>
    </head> 
    <body>
        <div id="conteneur" itemscope='itemscope' itemtype='http://schema.org/Blog'>
            <meta content='Melmelboo' itemprop='name'/>
            <header>
                <div id="header" onclick="location.href='/'"></div>
            </header>
            <div class="menuBlock social_mobile">
                <hr id="tophr" />
                <ul class="social">
                    <li><a title="Instagram" href="http://instagram.com/melmelbooo"><img class="social_icon" src="/images/social/instagram.png" alt="Instagram" /></a></li>
                    <li><a title="Facebook" href="http://www.facebook.com/melmelboo"><img class="social_icon" src="/images/social/facebook.png" alt="Facebook" /></a></li>
                    <li><a title="Hellocoton" href="http://www.hellocoton.fr/mapage/melmelboo"><img class="social_icon" src="/images/social/hellocoton.png" alt="Hellocoton" /></a></li>
                    <li><a title="Pinterest" href="http://www.pinterest.com/melmelboo"><img class="social_icon" src="/images/social/pinterest.png" alt="Pinterest" /></a></li>
                    <li><a title="Flux RSS" href="http://www.melmelboo.fr/RSS/articles.rss"><img class="social_icon" src="/images/social/feed.png" alt="RSS" /></a></li>
                </ul>
            </div>
            <hr id="tophr" />
            <div id="main">
                <div id="contenu">
                    <?php if (!empty($_speedmsg)) { ?>
                        <p>
                            <?php foreach ($_speedmsg as $msg) {
                                echo $msg."<br />";
                            } ?>
                        </p>
                    <?php } ?>
                    <?php echo $_view_str; ?>
                </div>
                <aside>
                    <div class="menuBlock">
                        <h1 class="menu_title">Qui suis-je ?</h1>
                        <a href="/about">
                            <img style="margin-bottom: 20px; width:237px;" src="/images/Moi.png" alt="À propos" />
                        </a>
                        <div class="title-font" id="contact-div">
                            <a href="/contact">
                                <h1 class="menu_title">Pour m'écrire, c'est ici</h1>
                                <img id="contact-arrow" src="/images/fleche.jpg" alt="fleche" />
                                <img src="/images/enveloppe.jpeg" alt="enveloppe" />
                            </a>
                        </div>
                    </div>
                    <div class="menuBlock">
                        <h1 class="menu_title">Suivez moi</h1>
                        <ul class="social">
                            <li><a title="Instagram" href="http://instagram.com/melmelbooo"><img src="/images/social/instagram.png" alt="Instagram" /></a></li>
                            <li><a title="Facebook" href="http://www.facebook.com/melmelboo"><img src="/images/social/facebook.png" alt="Facebook" /></a></li>
                            <li><a title="Hellocoton" href="http://www.hellocoton.fr/mapage/melmelboo"><img src="/images/social/hellocoton.png" alt="Hellocoton" /></a></li>
                            <li><a title="Pinterest" href="http://www.pinterest.com/melmelboo"><img src="/images/social/pinterest.png" alt="Pinterest" /></a></li>
                            <li><a title="Flux RSS" href="http://www.melmelboo.fr/RSS/articles.rss"><img src="/images/social/feed.png" alt="RSS" /></a></li>
                        </ul>
                    </div>
                    <div class="menuBlock">
                        <a href="http://instagram.com/melmelbooo/#">
                            <h1 class="menu_title">Instagram</h1>
                        </a>
                        <iframe src="http://widget.stagram.com/in/melmelbooo/?s=75&w=3&h=3&b=0&p=5" allowtransparency="true" frameborder="0" scrolling="no"
                            style="border:none;overflow:hidden;Width:237px; height: 237px; margin-bottom: 10px;"></iframe>
                    </div>
                    <div class="menuBlock">
                        <h1 class="menu_title">Recherche</h1>
                        <?php echo $_widgets['search']; ?>
                        <?php echo $_widgets['tag_cloud']; ?>
                    </div>
                    <div class="menuBlock">
                        <h1 class="menu_title">Projet 52</h1>
                        <?php echo $_widgets['project_52']; ?>
                    </div>
                    <div class="clear"></div>
<!--                    <nav id="menuBlock">
                        <h1 class="menu_title">Archives</h1>
                        <?php echo $_widgets['archives']; ?>
                    </nav>-->
                </aside>
            </div>
            <footer id="footer">
                <a id="admin_link" href="/admin">- Admin -</a>
            </footer>
        </div>
    </body> 
</html> 
<?php
$Racine_abs = str_replace($_SERVER['PHP_SELF'],"",$_SERVER['SCRIPT_FILENAME']);
$nom_page=$_SERVER['REQUEST_URI'];
require $Racine_abs.'/modules/allmystats/visiteur.php';
?> 
