<?php
$nom_page='page à propos';
$Racine_abs = str_replace($_SERVER['PHP_SELF'],"",$_SERVER['SCRIPT_FILENAME']);
require $Racine_abs.'/modules/allmystats/visiteur.php';
?> 
<div class="post">
<div class="mainpost">
<div class="postcontent">
    <strong>Qui je suis ?</strong>
    <br/><br/>

    Camille, 24 ans, parisienne depuis 2 ans. Pour le reste je vous laisse découvrir !
    <br/><br/>

    <strong>Pourquoi ce blog ?</strong>
    <br/><br/>

    Parce que j'adore partager mes idées, mes trouvailles, les détails de rien qui font tout. Parce que j'aime prendre en photo l'univers dans lequel j'évolue. Parce que ça m'oblige à toujours avancer, être curieuse, m'améliorer. Et parce que des lecteurs fidèles me suivent depuis des années et me donnent envi de continuer. Ici c'est un petit univers à moi où tout est possible, où je me sens libre et qui est, je crois, à mon image.  
    <br/><br/>

    <strong>Pourquoi MELMELBOO ? </strong>
    <br/><br/>

    Parce que c'est le pseudo que j'ai trouvé et utilisé sur le web lorsqu'il a fallu me créer une identité unique, anonyme et originale il y a plusieurs années déjà et qu'il me suit depuis le début. 
    <br/><br/>

    <img style="width: 100%;" src="/img/About/About01.JPG" alt="Révisions" />
    <img style="width: 100%;" src="/img/articles/paris/About04.JPG" alt="About" />

    <img style="width: 100%;" src="/img/articles/paris/About08.JPG" alt="About" />

    <img style="width: 100%;" src="/img/articles/paris/About05.JPG" alt="About" />

    <img style="width: 100%;" src="/img/articles/paris/About07.JPG" alt="About" />

    <img style="width: 100%;" src="/img/articles/paris/About09.JPG" alt="About" />
</div>
</div>
</div>
