<h1>Retailler des images</h1>
<ul>
    <li>Mettre toutes les images dans un même dossier (sur le Bureau par exemple)</li>
    <li>Ouvrir un terminal</li>
    <li>Écrire la commande suivante : « script_resize Bureau/mon_dossier »</li>
    <li>Attendre la fin du script qui signale son avancement fichier par fichier</li>
</ul>
<h1>Kit de Survie HTML</h1>

Pour de la présentation rapide des articles il faut utiliser du html.<br/>
Voici les balises principales que vous pouvez utiliser : <br/>

<ul>
	<li>
		Les balises titre : &lt;h1&gt;Mon titre en grand&lt;/h1&gt; donne <h1>Mon titre en grand</h1>. 
		On peut aussi faire la même chose avec h2 h3 h4 h5 et h6. Sachant que h1 est plus grand que h2 qui est plus grand que h3 ... 
	</li>
	<li>
		Forcer le retour à la ligne : &lt;br/&gt;
	</li>
	<li>
		Mettre en gras : &lt;strong&gt;Mon texte en gras&lt;/strong&gt;
	</li>
	<li>
		Mettre en italique : &lt;em&gt;Mon texte en italique&lt;/em&gt;
	</li>
	<li>
		Souligner : &lt;span style="text-decoration:underline;"&gt;Mon texte en souligne&lt;/span&gt;
	</li>
	<li>
		Mettre en couleur : &lt;span style="color:#B44884;"&gt;Mon texte en couleur&lt;/span&gt;
	</li>
	<li>
		Faire un lien : &lt;a href="http://MonAdresseDeLaMortQuiTueToutLeMonde"&gt;Text cliquable&lt;/a&gt;
	</li>
	<li>
		Inserer une image : &lt;img src="http://MonAdresseDeMaSuperbeImage" alt="Mon texte alternatif pour les pov' choux qui peuvent pas afficher l'image" /&gt;
	</li>
	<li>
		Faire une liste : <br/>
			&lt;ul&gt;<br/>
			&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;Mon element 1&lt;/li&gt;<br/>
			&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;Mon element 2&lt;/li&gt;<br/>
			&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;Mon element 3&lt;/li&gt;<br/>
			&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;...&lt;/li&gt;<br/>
			&lt;/ul&gt;
	</li>
</ul>

Pour approfondir : <a href="http://www.siteduzero.com/">Le Site Du Zero</a>
