<div class="comconteneur">
	<form method="post" action="">
        <h3 id="leavecom">Édition de la page liens</h3>
        <textarea class="new_art" name="content" id="commentaire"><?php echo $view->links_content; ?></textarea><br /><br />
        <input type="submit" value="Envoyer" />
	</form>
	Besoin d'aide pour de la mise en page ? <strong><a target="_blank" href="helphtml">C'est par ici.</a></strong> (Attention si tu ne veux pas perdre ce que tu es en train d'écrire, ouvre le lien dans un nouvel onglet.)
</div>
