<?php
$month_fr = array(
    1 => "Janvier",
    2 => "Février",
    3 => "Mars",
    4 => "Avril",
    5 => "Mai",
    6 => "Juin",
    7 => "Juillet",
    8 => "Août",
    9 => "Septembre",
    10 => "Octobre",
    11 => "Novembre",
    12 => "Décembre");
foreach ($view->months as $month_array) {
    $month = $month_array['month_int'];
	?><ul style="display:none;" class="archive_month_list">
    <li>
        <a href="archive-<?php echo $month . '-' . $view->year; ?>" class="archive_month">
            <?php echo $month_fr[$month]; ?>
        </a>
    </li>
</ul><?php } ?>
