-- --------------------------------------------------------

-- 
-- Structure de la table `allmystats_crawler`
-- 

CREATE TABLE `allmystats_crawler` (
  `id_crawler` smallint(5) unsigned NOT NULL auto_increment,
  `crawler_user_agent` varchar(255) default NULL,
  `org_name` varchar(45) NOT NULL default '',
  `bot_name` varchar(45) default NULL,
  `crawler_url` varchar(255) default NULL,
  `crawler_info` varchar(255) default NULL,
  `crawler_ip` varchar(16) default NULL,
  PRIMARY KEY  (`id_crawler`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=405 ;

-- 
-- Contenu de la table `allmystats_crawler`
-- 

INSERT INTO `allmystats_crawler` (`id_crawler`, `crawler_user_agent`, `org_name`, `bot_name`, `crawler_url`, `crawler_info`, `crawler_ip`) VALUES 
(1, NULL, 'Google Image', 'Googlebot-Image', 'http://images.google.com/', '', NULL),
(2, NULL, 'Google-Adsense', 'Mediapartners-Google', NULL, '', NULL),
(3, NULL, 'FeedFetcher-Google', 'FeedFetcher-Google', NULL, '', NULL),
(4, NULL, 'Google-Sitemaps', 'Google-Sitemaps', NULL, '', NULL),
(5, NULL, 'Google', 'Googlebot', NULL, '', NULL),
(6, NULL, 'Yahoo!', 'Yahoo! Slurp', NULL, '', NULL),
(7, NULL, 'Altavista', 'Scooter', 'http://www.altavista.com', 'Moteur de recherche', NULL),
(8, NULL, 'Gigablast', 'Gigabot', 'http://www.gigablast.com/spider.html', 'Moteur de recherche', NULL),
(9, NULL, 'Sogou', 'Sogou web spider', 'http://www.sogou.com/docs/help/webmasters.htm#07', 'Chinese Search Engine', NULL),
(10, NULL, 'Voila', 'VoilaBot', 'http://www.voila.com', '', NULL),
(11, NULL, 'MSN', 'msnbot', 'http://search.msn.com/msnbot.htm', '', NULL),
(12, NULL, 'entireweb', 'Speedy Spider', 'http://www.entireweb.com', 'Moteur de recherche', NULL),
(13, NULL, 'www.cuill.com', 'Twiceler', 'http://www.cuill.com/twiceler/robot.html', 'Moteur de recherche trés bien.', NULL),
(14, NULL, 'www.super.info', 'superbot.com', 'http://www.super.info', 'Moteur de recherche', NULL),
(15, NULL, 'Exalead', 'Exabot', 'http://www.exalead.fr', 'Moteur de recherche', NULL),
(16, NULL, 'www.baidu.com', 'Baiduspider', 'http://www.baidu.com/search/spider_jp.html', 'Chinese Search Engine', NULL),
(17, NULL, 'soso.com', 'Sosoimagespider', 'http://www.soso.com', 'Chinese picture Search Engine', NULL),
(18, NULL, 'www.discoveryengine.com', 'discobot', 'http://www.discoveryengine.com/discobot.html', 'Discobot is the experimental web crawler', NULL),
(19, NULL, 'www.shopwiki.com', 'ShopWiki', 'http://www.shopwiki.com/wiki/Help:Bot', '', NULL),
(20, NULL, 'GnoZtiK', 'GnoZtiK bot', 'http://www.gnoztik.com/', 'Site pour optimiser le référencement', NULL),
(21, NULL, 'www.yandex.ru', 'Yandex', 'http://www.yandex.ru', 'Moteur de recherche Russe', NULL),
(22, NULL, 'Xenu Link', 'Xenu Link', 'http://www.google.fr/search?hl=fr&q=xenu&btnG=Rechercher&meta=lr%3Dlang_fr', 'Test des liens morts', NULL),
(23, NULL, 'libwww-perl', 'libwww-perl', 'http://search.cpan.org/dist/libwww-perl/', 'Attention, il peut chercher des failles', NULL),
(24, NULL, 'Alexa Web Search', 'ia_archiver', 'http://www.alexa.com', 'Statistiques sites', NULL),
(26, NULL, 'Whois Source', 'SurveyBot', 'http://www.whois.sc/info/webmasters/surveybot.html', 'www.whois.sc', NULL),
(27, NULL, 'ask', 'Ask Jeeves', 'http://fr.ask.com', 'Moteur de recherche', NULL),
(28, NULL, 'DMOZ', 'Robozilla', 'http://www.dmoz.org', 'Open Directory Project', NULL),
(29, NULL, 'Sqworm', 'Sqworm', NULL, 'No idea about this one', NULL),
(30, NULL, 'Microsoft', 'msnbot-media', 'http://search.msn.com/msnbot.htm', '', NULL),
(31, NULL, 'Larbin', 'larbin_2.6.3', 'http://larbin.sourceforge.net/index-eng.html', 'Multi-purpose web crawler', NULL),
(32, NULL, 'betaBot', 'betaBot', NULL, 'Pas d''info', NULL),
(33, NULL, 'www.scoutjet.com', 'ScoutJet', 'http://www.scoutjet.com', 'ScoutJet est le robot d''exploration du Web pour une nouvelle Silicon Valley moteur de recherche créé par les fondateurs de DMOZ et Topix.', NULL),
(34, NULL, 'gossamer-threads.com', 'Links SQL', 'http://gossamer-threads.com', '', NULL),
(35, NULL, 'HTTPConnect', 'HTTPConnect', '', 'Aspirateur de site', NULL),
(36, NULL, 'Heritrix', 'heritrix/2.0.0', 'http://crawler.archive.org', 'Internet Archive''s open-source', NULL),
(37, NULL, 'www.snap.com', 'Snapbot/1.0', 'http://www.snap.com', '', NULL),
(38, NULL, 'Commoncrawl', 'CCBot/1.0', 'http://www.commoncrawl.org/bot.html', '', NULL),
(39, NULL, 'HTMLParser', 'HTMLParser', 'http://htmlparser.sourceforge.net/', 'Extraction des liens d’une page web', NULL),
(40, NULL, 'Ichiro', 'Ichiro', 'http://help.goo.ne.jp/door/crawler.html', 'Chinese Search Engine', NULL),
(41, NULL, 'Nutch', 'nutch/Nutch', 'http://lucene.apache.org/nutch/bot.html', 'Open source project', NULL),
(42, NULL, 'FDSE robot', 'FDSE robot', NULL, '', NULL),
(43, NULL, 'RAYSPIDER/Nutch-0.9', 'RAYSPIDER/Nutch-0.9', NULL, 'I can''t find much info on this', NULL),
(44, NULL, 'Exooba', 'exooba crawler/0.5.1', 'http://www.exooba.com', 'exooba crawler for exooba search pre-alpha development', NULL),
(48, NULL, 'AdsBot-Google', 'AdsBot-Google', 'http://www.google.com/adsbot.html', 'AdWords', NULL),
(49, NULL, 'QEAVis', 'QEAVis agent/Nutch-0.9', 'http://nlp.uned.es/qeavis', NULL, NULL),
(50, NULL, 'Google', 'Google Keyword Tool', 'https://adwords.google.com/select/KeywordToolExternal', 'Générateur de mots clés', NULL),
(51, NULL, 'Exalead', 'NG/2.0', 'http://www.exalead.com/cgi/exalead', 'Moteur de recherche', NULL),
(52, NULL, ' ? Onetime Program ?', 'Onetime Program', NULL, NULL, NULL),
(53, NULL, 'page_verifier', 'page_verifier', 'http://www.securecomputing.com/goto/pv', NULL, NULL),
(54, NULL, 'Tipiweb/Nutch-0.9', 'Tipiweb/Nutch-0.9', NULL, 'Pas d''info', NULL),
(55, NULL, 'www.visvo.com', 'VisBot/2.0', 'http://www.visvo.com/bot.html', 'Petit moteur de recherche qui ne fonctionne pas bien.', NULL),
(56, NULL, 'www.rankiva.com', 'Rankivabot', 'http://www.rankiva.com', 'Rankiva is an online tool that ranks websites.', NULL),
(57, NULL, 'gossamer-threads.com', 'Links 2.0', 'http://gossamer-threads.com/scripts/links/', NULL, NULL),
(58, NULL, 'Java/1.6.0_10-beta', 'Java/1.6.0_10-beta', NULL, 'First Seen On: 24/05/2008', NULL),
(59, NULL, 'Scrubby', 'Scrubby', 'http://www.scrubtheweb.com/abs/meta-check.html', 'META Tag Analyzer', NULL),
(60, NULL, 'Python-urllib', 'Python-urllib', 'http://www.lib.uchicago.edu/keith/courses/python/class/7/', 'Phyton Module for fetching data across the World Wide Web', NULL),
(61, NULL, 'Cyberpatrol', 'CyberPatrol SiteCat Webbot', 'http://www.cyberpatrol.com/cyberpatrolcrawler.asp', 'Logiciel de contrôle parental', NULL),
(62, NULL, 'Flatlandindustries', 'flatlandbot/flatlandbot', 'http://www.flatlandindustries.com', 'Experimental Web Index', NULL),
(63, NULL, 'Metadatalabs', 'MLBot', 'http://www.metadatalabs.com/mlbot', NULL, NULL),
(64, NULL, 'kalooga', 'KaloogaBot', 'http://www.kalooga.com', 'Moteur de recherche', NULL),
(65, NULL, 'Grub', 'Grub/2.0', 'http://www.grub.org', NULL, NULL),
(66, NULL, 'Exalead', 'Exabot-Thumbnails', 'http://www.exalead.com', 'Exabot-Thumbnails ne genere des thumbnails que pour les urls crawlées par Exabot', NULL),
(67, NULL, 'Yahoo! Slurp China', 'Yahoo! Slurp China', 'http://misc.yahoo.com.cn/help.html', NULL, NULL),
(68, NULL, 'Yahoo!', 'BonEcho/2.0.0.4', NULL, NULL, NULL),
(69, NULL, 'Yahoo! DE', 'Yahoo! DE Slurp', 'http://help.yahoo.com/help/us/ysearch/slurp', NULL, NULL),
(70, NULL, 'DotBot', 'DotBot/1.0.1', 'http://www.dotnetdotcom.org', NULL, NULL),
(71, NULL, 'Amfibi\\''s web-crawling', 'Cabot/Nutch-0.9', 'http://www.amfibi.com/cabot/', 'Moteur de recherche', NULL),
(72, NULL, 'Majestic-12', 'MJ12bot/v1.2.1', 'http://www.majestic12.co.uk/bot.php?+', NULL, NULL),
(73, NULL, 'Acoon', 'Acoon-Robot 4.0.2.17', 'http://www.acoon.de', 'Moteur de recherche Allemand', NULL),
(74, NULL, 'BrightCloud', 'BrightCrawler', 'http://www.brightcloud.com/brightcrawler.asp', NULL, NULL),
(75, NULL, 'Crawl Annu', 'Crawl Annu', NULL, 'Inconnu', NULL),
(76, NULL, 'Eurobot/Nutch', 'Eurobot/Nutch-1.0-dev', NULL, 'Inconnu', NULL),
(77, NULL, 'www.snap.com', 'SnapPreviewBot', 'http://www.snap.com', 'Snap Firefox Search Plugin', NULL),
(78, NULL, 'Yeti', 'Yeti/1.0', 'http://help.naver.com/robots/', 'chinese bot', NULL),
(79, NULL, 'Amfibi''s web-crawling', 'Cabot/Nutch-1.0-dev', 'http://www.amfibi.com/cabot/', 'Amfibi''s web-crawling robot', NULL),
(80, NULL, 'Microsoft isrc-bot', 'MSR-ISRCCrawler', NULL, '', NULL),
(81, NULL, 'panscient.com', 'panscient.com', '', 'Panscient explore le Web et recueille des informations sur les personnes et les entreprises pour des applications de recherche', NULL),
(82, NULL, 'therarestwords', 'TheRarestParser/0.2a', 'http://therarestwords.com', 'The Rarest Words - Linguistic experiment crawler via Amazon Web Services', NULL),
(83, NULL, 'www.wauuu.com', 'wauuu engine/Wauuu 0.1', 'http://www.wauuu.com', NULL, NULL),
(84, NULL, 'Microsoft Corporation', 'MSNPTC/Test', 'http://msn.com', 'No information available', NULL),
(85, NULL, 'OpenAcoon', 'OpenAcoon v4.0.3', 'http://www.openacoon.de', NULL, NULL),
(86, NULL, 'compatible; Indy Library', 'compatible; Indy Library', NULL, 'Pas d''info', NULL),
(87, NULL, 'holmes/3.12', 'holmes/3.12', 'http://morfeo.centrum.cz/bot', 'Pas d''info', NULL),
(88, NULL, 'OpenAcoon', 'OpenAcoon v4.0.5', 'http://www.openacoon.de', NULL, NULL),
(90, NULL, '', 'shelob v1.0', '', 'Bad bot', NULL),
(91, NULL, 'NetWhat', 'NetWhatCrawler/0.06-dev', 'http://www.netwhat.com', 'Moteur de recherche', NULL),
(92, NULL, 'Exooba', 'exooba crawler/exooba', 'http://www.exooba.com', 'exooba crawler for exooba search pre-alpha development', NULL),
(93, NULL, 'Exooba', 'exooba/exooba', 'http://www.exooba.com', 'exooba crawler for exooba search pre-alpha development', NULL),
(94, NULL, 'Thumbshots', 'thumbshots-de-bot', 'http://www.thumbshots.de', NULL, NULL),
(95, NULL, 'Moreover', 'Moreoverbot/5.00', 'http://www.moreover.com', NULL, NULL),
(96, NULL, 'MSIECrawler', 'MSIECrawler', NULL, 'MSIECrawler is not a true web robot. It is usually to be found in site logs if someone bookmarks a page whilst offline. Internet Explorer will then download the page and all links related to it, including links, images, JavaScript and Style sheets, when t', NULL),
(97, NULL, 'www.myengines.org', 'MyEngines-Bot', 'http://www.myengines.org', NULL, NULL),
(98, NULL, 'NetEase', 'YodaoBot/1.0', 'http://www.163.com/', 'NetEase is known for its popular Chinese portal 163.com. It was using Google as its search engine till the middle of 2007, when it decided to replace it by yodao, its own search engine.', NULL),
(99, NULL, 'Microsoft', 'MSRBOT', 'http://research.microsoft.com/research/sv/msrbot/', 'We are using the MSRBot web crawler to collect data from the web for further study.', NULL),
(100, NULL, 'quickengines.com', 'Jeanie_2008_bot/3.2', 'http://www.quickengines.com', NULL, NULL),
(101, NULL, 'PhpDig.net', 'PhpDig/1.8.0', 'http://www.phpdig.net/robot.php', NULL, NULL),
(102, NULL, 'Nokia find.mobi', 'Nokia6300/2.0', 'http://find.mobi/bot.html', NULL, NULL),
(103, NULL, 'freedownloadmanager.org', 'FDM 2.x', 'http://www.freedownloadmanager.org/', 'Free Download Manager (FDM) download accelerator', NULL),
(104, NULL, 'GoogleToolbar', 'GoogleToolbar 2.0.111-big', NULL, NULL, NULL),
(105, NULL, 'Java/1.6.0_06', 'Java/1.6.0_06', NULL, NULL, NULL),
(106, NULL, 'Touche', 'Touche', 'http://www.touche.com.ve/', 'Search engine', NULL),
(107, NULL, 'www.semager.de', 'Semager/1.2', 'http://www.semager.de/blog/semager-bots/', NULL, NULL),
(108, NULL, 'www.sigram.com', 'Sigram/Nutch-1.0-dev', 'http://www.sigram.com/bot.html', 'Test agent for Nutch development', NULL),
(109, NULL, 'WebDataCentre.com', 'WebDataCentreBot/1.0', 'http://WebDataCentre.com/', 'Projet de recherche conduit par une petite équipe de chercheurs de différentes régions du monde.', NULL),
(110, NULL, 'Sqwidge', 'SqwidgeBot a0.3.23', 'http://www.sqwidge.com/bot/', 'Développement moteur de recherche', NULL),
(111, NULL, 'setooz.com', 'OOZBOT/0.17', 'http://www.setooz.com/oozbot.html', 'Moteur de recherche', NULL),
(112, NULL, 'rulinki.ru project', 'rulinki.ru project', '', 'Non indentifié', NULL),
(319, '', 'MailWalker', 'MailWalker', 'http://www.websynaptics.com/solutions.html', 'Extracteur d''emails', ''),
(317, '', 'Sogou', 'Sogou Pic Spider/3.0', 'http://www.sogou.com/docs/help/webmasters.htm#07', 'Chinese picture Search Engine', ''),
(315, '', 'Wikiwix', 'wikiwix-bot-3.0', 'http://www.wikiwix.com/', 'Wikipedia articles search engine', ''),
(320, '', 'Jakarta Commons-HttpClient/3.0.1', 'Jakarta Commons-HttpClient/3.0.1', 'http://hc.apache.org/httpclient-3.x/', '', ''),
(321, '', 'Yahoo', 'Yahoo-MMCrawler', 'http://www.robotstxt.org/wc/exclusion.html#robotstxt', 'Recherche d''images', ''),
(323, '', 'www.picsearch.com', 'psbot/0.1', 'http://www.picsearch.com/bot.html', 'PicSearch index des images à partir du Web.', ''),
(324, '', 'Yahoo!-AdCrawler', 'Yahoo!-AdCrawler', ' http://help.yahoo.com/yahoo_adcrawler', '', ''),
(325, '', 'Reedbusiness', 'CatchBot/1.0', 'http://www.catchbot.com', 'Reed Business Information propose de l’information et de l’espace de communication B to B à travers ses 3 métiers : presse, édition et formation.', ''),
(397, '', 'hrinktheweb.com', 'ShrinkTheWeb.com Crawler v1.0', 'http://www.shrinktheweb.com', 'Miniature en image de votre site (thumbnail).', ''),
(327, '', 'WorldSearch', 'Yanga WorldSearch Bot v1.1', 'http://www.yanga.co.uk', 'Moteur de recherche', ''),
(328, '', 'Guruji', 'GurujiBot/1.0', 'http://www.guruji.com/en/WebmasterFAQ.html', 'Moteur de recherche', ''),
(329, '', 'Turnitin', 'TurnitinBot/2.1', 'http://www.turnitin.com/robot/crawlerinfo.html', 'Site permetant aux professeurs de voir si les élèves ont copié sur des phrases sur Internet.', ''),
(341, '', 'FollowSite', 'FollowSite Bot', 'http://www.followsite.com/bot.html', 'Votre site web est important pour un (ou plusieurs) de nos utilisateurs et a été ajouté à FollowSite. Nous allons maintenant surveiller votre site et lui notifier quand il est mis à jour.', ''),
(344, '', 'Sapphire Web Crawler using Nutch', 'SapphireWebCrawler/Nutch-1.0-dev', 'http://boston.lti.cs.cmu.edu/crawler/', 'Le projet est la création d\\''une base de données de 1 milliard de pages web en 10 langues qui seront utilisées à des fins de recherche par les scientifiques du monde entier. Le projet est supervisé par le professeur Jamie Callan.', ''),
(345, '', 'Sapphire Web Crawler using Nutch', 'SapphireWebCrawler/1.0', 'http://boston.lti.cs.cmu.edu/crawler', 'Le projet est la création d\\''une base de données de 1 milliard de pages web en 10 langues qui seront utilisées à des fins de recherche par les scientifiques du monde entier. Le projet est supervisé par le professeur Jamie Callan.', ''),
(346, '', 'dotnetdotcom', 'DotBot/1.1', 'http://www.dotnetdotcom.org', '', ''),
(347, '', 'dontbuylists.com', 'DBLBot/1.0', 'http://www.dontbuylists.com', '', ''),
(348, '', 'askpeter', 'askpeter_bot_5.0', 'http://www.askpeter.info', 'Moteur de recherche', ''),
(349, '', 'majestic12.co.uk', 'MJ12bot/v1.2.3', 'http://www.majestic12.co.uk/bot.php', '', ''),
(364, '', 'kilomonkey.com', 'kmky-not-a-bot/0.2', 'http://www.kilomonkey.com/notabot.txt', 'Pas d''infos', ''),
(365, '', 'Flatland Industries Web Spider', 'flatlandbot/baypup', 'http://www.flatlandindustries.com/flatlandbot', '', ''),
(366, '', 'majestic12.co.uk', 'MJ12bot/v1.2.4', 'http://www.majestic12.co.uk/bot.php', '', ''),
(367, '', 'first-search.com', 'FirstSearchBot/1.0', 'http://www.first-search.com', 'Moteur de recherche', ''),
(375, '', 'gais.cs.ccu.edu.tw', 'Gaisbot/3.0', 'http://gais.cs.ccu.edu.tw/robot.php', 'Développement moteur de recherche', ''),
(376, '', 'apercite.fr', 'Apercite', 'http://www.apercite.fr/robot/index.html', 'Miniature en image de votre site.', ''),
(377, '', 'askpeter.info', 'askpeter_bot/5.0', 'http://www.askpeter.info', 'Moteur de recherche', ''),
(378, '', 'bibnum.bnf.fr', 'bnf.fr_bot', 'http://bibnum.bnf.fr/robot/bnf.html', 'Vous avez été renvoyé à cette page car votre site est actuellement collecté automatiquement par la Bibliothèque nationale de France (BnF).', ''),
(379, '', 'Nokia', 'Nokia6682/2.0', 'http://help.yahoo.com/help/us/ysearch/crawling/crawling-01.html', '', ''),
(380, '', 'Nokia', 'Nokia6680/1.0', '', '', ''),
(381, '', 'Apple mobile', 'AppleWebKit/420', '', '', ''),
(382, '', 'SimilarPages Nutch Crawler', 'SimilarPages/Nutch-1.0-dev', 'http://www.similarpages.com', 'Pas d''infos à ce jour', ''),
(383, '', '', 'digiSelf crawler/Nutch-1.0-dev', '', 'Pas d''infos à ce jour', ''),
(384, '', 'Flatland Industries Web Spider', 'flatlandbot/allspark', 'http://www.flatlandindustries.com/flatlandbot', '', ''),
(385, '', 'Robotgenius.net', 'robotgenius', 'http://robotgenius.net', '', ''),
(386, '', 'www.kosmix.com', 'voyager/2.0', 'http://www.kosmix.com/crawler.html', 'Il récupère des documents sur le Web pour construire l''indice du moteur de recherche Kosmix ', ''),
(387, '', 'yacy.net', 'yacybot', 'http://yacy.net/bot.html', '"yacybot" est le useragent du logiciel YaCy, qui est une approche pour construire un réseau de peer-to-Peer basée websearch-moteur.', ''),
(388, '', 'ODP link checker', 'pmoz.info ODP link checker', 'http://pmoz.info/doc/botinfo.htm', 'Vérifie des liens de l\\''annuaire Dmoz Open Directory Project', ''),
(393, '', 'OrangeBot-Mobile', 'OrangeBot-Mobile', '', '', ''),
(395, '', 'afholderbach.net', 'ecoNet', 'http://www.eco.afholderbach.net', '', ''),
(403, '', 'W3C Validator', 'W3C_Validator', 'http://validator.w3.org/', 'Test des pages web à la norme W3C', ''),
(399, '', 'LinguaSeek', 'LinguaSeek', 'http://www.linguaseek.com', 'Moteur de recherche', ''),
(400, '', 'Majestic-12', 'MJ12bot (mini)/1.0.0', 'http://search.majestic12.co.uk', 'Moteur de recherche', ''),
(404, '', 'W3C CSS Validator', 'W3C_CSS_Validator', 'http://jigsaw.w3.org/css-validator', 'Test W3C des feuilles CSS', '');
